### ISSUE TITLE
The Ability button (R) Doesn't work

### ISSUE THREAD

**Issue by Kaen-1** [Draylar/identity#100]
So I am having an issue where when I'm a creeper I cant use the ability and so with all the other mobs with the use of **R** it may just be because I use the **R** key to drop items but I also tried changing that and it still didn't work? maybe add a **keybind**

_sorry for my English if it was hard to read_

**Comment by Kaen-1** [comment]
nvm i have find the issue i was not using gunpowder sorry

**Comment by Kaen-1** [comment]
but could u add a way for you to see the player client side when morphed into a mob for example if i was on a server and morphed into a blaze i would see the player (me/the player's skin) and not the blaze model but the other players would still see the blaze i think that would be pretty nice!

**Comment by Draylar** [comment]
Gunpowder/items for abilities is only required on old versions of the mod. Make sure you are using the latest version; there will be an entry in your options page to configure the key if something else is bound to R.
