### ISSUE TITLE
´ Not working

### ISSUE THREAD

**Issue by Olsacostth** [Draylar/identity#101]
I just tried to use the mod for the first time and the ´ (transform) key did not work. Does anybody have the same issue? Everything else looks fine.

**Comment by Draylar** [comment]
Please send your game log through [hastebin](https://hastebin.com/).

**Comment by Moglibogli** [comment]
> I just tried to use the mod for the first time and the ´ (transform) key did not work. Does anybody have the same issue? Everything else looks fine.

i am also having the same issue. im on a server and when i press the transform keybind it freezes for a bit then crashes the client

**Comment by Olsacostth** [comment]
I forgot to turn the right options on, so i sadly do not have the game log.

**Comment by TheServerit** [comment]
> > I just tried to use the mod for the first time and the ´ (transform) key did not work. Does anybody have the same issue? Everything else looks fine.
> 
> i am also having the same issue. im on a server and when i press the transform keybind it freezes for a bit then crashes the client

Yeah, it's really ANNOYING. how can you FIX it??

**Comment by TheServerit** [comment]
> Please send your game log through [hastebin](https://hastebin.com/).

That's not what you're thinking. It's not sending ANYTHING. no game log. Game crashers, without ANY LOG.

**Comment by TheServerit** [comment]
PLEASE help me.... ):

**Comment by TheServerit** [comment]
PLEASE

**Comment by Draylar** [comment]
Do **not** spam issues. The game always has a log. Search on YouTube if you need assistance finding it. The original poster has not posted a game log, so I am closing this. If you still encounter the crash, please open a new issue with your game log.

**Comment by TheServerit** [comment]
I'm trying to tell you, it's a "special" crash, without a game log. just a crash without something more... I swear...
