### ISSUE TITLE
(R) does not work (Morph button)

### ISSUE THREAD

**Issue by TheAmazingLink9** [Draylar/identity#108]
I know there is one for this but Im on 1.16.5 and it is not working at all so I was wondering if the button changed or anything. I have checked about 5 times to see if something is not working because of a button. HELP

**Comment by Draylar** [comment]
The button to change identities is ` (the key to the left of 1). R is the key to use abilities. Abilities only work on certain mobs. Can you clarify what you are trying to do?

**Comment by Orangenal-name** [comment]
I am having this same issue, if I press R with a blaze or an enderman (those are just the only two I have tried) I do not teleport or shoot fireballs

**Comment by TheAmazingLink9** [comment]
Nvm I was using the 1.16.3 version of Fabric when the mod was for 1.16.4 sorry

**Comment by TheAmazingLink9** [comment]
Sorry for wasting your time

**Comment by Draylar** [comment]
No worries. Orange, if you still encounter those issues on the latest version of Identity, feel free to open a new issue with your game log and version details.
