### ISSUE TITLE
Hitbox is offset when changing Identities

### ISSUE THREAD

**Issue by James103** [Draylar/identity#11]
Minecraft 1.16.1
Fabric 0.8.8+build.202
LWJGL 3.2.2
Fabric API 0.14.0+build.371-1.16
Identity 1.1.0-beta-1.16

![image](https://user-images.githubusercontent.com/37945304/85943086-54f30d80-b8f3-11ea-8c08-9184a8e986e9.png)
(this was after changing from Ghast to default player)

**Comment by James103** [comment]
A similar bug occurs in vanilla 1.16.1 when, for example, a Baby Turtle grows up into an adult, which can easily be reproduced with `/summon turtle ~ ~ ~ {Age:-20}`. In other words, this is a vanilla bug.

Note that it can even be reproduced in 20w28a with a Zombie by setting the IsBaby tag from 1 to 0. See https://youtu.be/xcQhAth2bpQ?t=423

**Comment by Draylar** [comment]
Fixed in the next update... there was a server-only check in the hitbox updating code that I copied from vanilla.
