### ISSUE TITLE
Crash When Joining server

### ISSUE THREAD

**Issue by TeamRIS** [Draylar/identity#110]
log: ---- Minecraft Crash Report ----
// There are four lights!

Time: 2021-01-21 11:58:00 IST
Description: Unexpected error

java.util.NoSuchElementException: class_5419['Piglin Brute'/106, l='ClientLevel', x=-668.33, y=44.00, z=546.81] provides no component of type identity:current_identity
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7)
    at nerdhub.cardinal.components.api.ComponentType.get(ComponentType.java:109)
    at net.minecraft.entity.LivingEntity.handler$big000$returnHasNightVision(LivingEntity:9453)
    at net.minecraft.entity.LivingEntity.hasStatusEffect(LivingEntity)
    at net.minecraft.client.render.BackgroundRenderer.render(BackgroundRenderer:172)
    at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1116)
    at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:727)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:546)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  All players: 1 total; [class_746['Souldbminer'/105, l='ClientLevel', x=-668.33, y=44.00, z=546.81]]
  Chunk stats: SodiumChunkCache: 169
  Level dimension: minecraft:the_nether
  Level spawn location: World: (91,97,-56), Chunk: (at 11,6,8 in 5,-4; contains blocks 80,0,-64 to 95,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Level time: 176518715 game time, 6642041 day time
  Server brand: fabric
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 4042566008 bytes (3855 MB) / 6039797760 bytes (5760 MB) up to 12884901888 bytes (12288 MB)
  CPUs: 12
  JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Fabric Loader (fabricloader), Cardinal Components API (base) (cardinal-components-base)
  Fabric Mods: additionalbars: Additional Bars 1.0.1
               adorn: Adorn 1.12.0+1.16.4
               allstackable: All Stackable 1.2.6
               amecsapi: Amecs API 1.1.1+mc1.16-rc1
               angerable-patch: Angerable Patch 1.0.0-1.16.1
               appleskin: AppleSkin 1.0.11
               artifice: Artifice 0.13.1+1.16.2-rc1
               autoconfig1u: Auto Config v1 Updated 3.3.1
               bebooks: Better Enchanted Books 1.1.4
               bendy-lib: Bendy api 0.2.3
               betterend: Better End 0.6.2-beta
               betternether: Better Nether 5.0.3
               blockshifter: Blockshifter 1.3.2+fabric-1.16.4
               blue_endless_jankson: jankson +
               byg: BYG 1.1.2
               cardinal-components-base: Cardinal Components API (base) 2.7.2
               cardinal-components-entity: Cardinal Components API (entities) 2.7.2
               carrier: Carrier 1.4.0
               chainmail: Chainmail 0.5.0
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.5
               cloth-config2: Cloth Config v4 4.8.3
               cotton-client-commands: Cotton Client Commands 1.0.0+1.15.2
               craftpresence: CraftPresence 1.7.5
               croptopia: Croptopia 1.0.5-1.16.3-FABRIC
               dwarfcoal: Dwarf Coal 1.16.2-1.0.0
               dynamicfps: Dynamic FPS 1.2.1
               emotecraft: Emotecraft 1.2.4
               expandedstorage: ExpandedStorage 5.6.31
               ezpas: Ezpas 1.2.3-1.16.2
               fabric: Fabric API 0.29.3+1.16
               fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
               fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
               fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
               fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
               fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+8004b36d3a
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5ba7
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
               fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
               fabric-language-scala: Fabric Language Scala 0.3.2.12
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
               fabric-models-v0: Fabric Models (v0) 0.2.0+cbe9176f3a
               fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
               fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
               fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+cbe9176f3a
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
               fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+c26373133a
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.1+0d4d7e343a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
               fabricloader: Fabric Loader 0.10.8
               fabritone: Fabritone 1.6.2
               fallflyinglib: FallFlyingLib 1.1.0
               fancymenu: FancyMenu 1.6.0
               fiber: fiber 0.23.0-1
               flan: Flan 1.16.2-1.1.4
               givemehats: Give Me Hats! 1.2.8
               glassdoor: Glass Doors 1.5.0-1.16
               go-fish: Go Fish 1.1.0-beta-1.16.4
               greater_eye: Greater Eye of Ender 1.1.3
               healthoverlay: Health Overlay 3.6.12
               hen6003_mi: MI - Movement Info 1.3.4
               identity: Identity 1.10.2-beta-1.16.3
               inventorysorter: Inventory Sorter 1.7.4-1.16
               io_github_onyxstudios_cardinal-components-api: Cardinal-Components-API 2.7.1
               jankson: Jankson 3.0.1+j1.2.0
               jumpoverfences: JumpOverFences 1.16-0.0.3
               kibe: Kibe 1.5.2-BETA
               konkrete: Konkrete 1.1.1
               kyrptconfig: Kytpt Config 1.1.2-1.16
               libblockattributes_core: LibBlockAttributes (Core) 0.8.3-pre.3
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.3-pre.3
               libcd: LibCapableData 3.0.3+1.16.3
               libgui: LibGui 3.2.2+1.16.3
               linkart: Linkart unspecified
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               loadcatcher: Entrypoint Catcher 2.0.0
               magna: Magna 1.4.2-1.16.2
               meteor-client: Meteor Client 0.3.9
               minecraft: Minecraft 1.16.4
               minecraftcapes: MinecraftCapes Mod 10
               mo_glass: Mo Glass 1.5-MC1.16.4
               modmenu: Mod Menu 1.14.8+build.12
               mousewheelie: Mouse Wheelie 1.5.10+mc1.16.4
               mycommands: MyCommands Fabric 1.16.1-17
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.4
               olifantenpad: Olifantenpad 1.0.0
               org_aperlambda_lambdajcommon: lambdajcommon 1.8.0
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
               org_yaml_snakeyaml: snakeyaml 1.25
               phosphor: Phosphor 0.6.0+build.7
               playerabilitylib: Pal 1.2.1
               reborncore: Reborn Core 4.6.1+build.97
               repurposed_structures: Repurposed Structures 1.16.3-1.6.9
               respawnablepets: Respawnable Pets 1.16.4-1
               ringsofascension: Rings of Ascension 1.1.1
               roughlyenoughitems: Roughly Enough Items 5.8.3
               roughlyenoughitems-api: REI (API) 5.8.3
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.3
               roughlyenoughitems-runtime: REI (Runtime) 5.8.3
               roughlyenoughresources: Roughly Enough Resources 2.1.2
               rpg-hud: RPG-Hud 3.8.1
               secretrooms: Secret Rooms 0.9.2+1.16.2
               simpleteleporters: Simple Teleporters 2.2.1
               smoothboot: Smooth Boot 1.2.2
               sodium: Sodium 0.1.0
               staffofbuilding: Staff of Building 1.2.3-1.16.2
               team_reborn_energy: Energy 0.1.0
               tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
               transferchestmod: Transfer Chest 1.1.2
               trinkets: Trinkets 2.6.7
               truerooms: True Secret Rooms 1.0.3
               tweed: Tweed API 3.0.0-beta.20
               vanillaexcavators: Vanilla Excavators 1.1.0
               villagerhats: Villager Hats fabric-1.16.4-1.0.1
               visualoverhaul: VisualOverhaul 1.0.0
               voyager: Voyager 1.0.0
               waystones: Waystones 1.0.9
               winged: Winged Mod 1.16.2-1.4.1
               woods_and_mires: Woods and Mires 1.0.3+1.16.3
               worldedit: WorldEdit 7.2.0+a51fa43
               xaerominimap: Xaero's Minimap 20.27.2
               xaeroworldmap: Xaero's World Map 1.11.0
  Launched Version: fabric-loader-0.10.8-1.16.4
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Graphics mode: fancy
  Resource Packs: vanilla, secretrooms:client_pack, Fabric Mods, visualoverhaul/nobottles
  Current Language: English (US)
  CPU: 12x AMD Ryzen 5 3600 6-Core Processor
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

-- Meteor Client --
Version: 0.3.9

[Combat]:
Auto Totem (auto-totem)
Criticals (criticals)
Kill Aura (kill-aura)
Offhand Extra (offhand-extra)
Totem Pop Notifier (totem-pop-notifier)

[Player]:
Anti Cactus (anti-cactus)
Anti Hunger (anti-hunger)
Mount Bypass (mount-bypass)
XCarry (XCarry)

[Movement]:
Anti Levitation (anti-levitation)
Boat Fly (boat-fly)
Elytra+ (Elytra+)
Entity Control (entity-control)
Entity Speed (entity-speed)
Fast Ladder (fast-ladder)
Jesus (jesus)
No Fall (no-fall)
No Slow (no-slow)

[Render]:
Camera Clip (camera-clip)
Esp (esp)
Full Bright (full-bright)
HUD (HUD)
Hole Esp (hole-esp)
Logout Spots (logout-spots)
No Render (no-render)
Storage Esp (storage-esp)
Tracers (tracers)
Trajectories (trajectories)
Unfocused Cpu (unfocused-cpu)

[Misc]:
Anti Packet Kick (anti-packet-kick)
Auto Reconnect (auto-reconnect)
Better Chat (better-chat)
Discord Presence (discord-presence)
EChest Preview (EChest-preview)

**Comment by Draylar** [comment]
Fixed in the next update, thank you for letting me know 👍
