### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by TBXYT** [Draylar/identity#114]
Hello, im a big fan of this mod but i have some problems. My friend has a "Anne Pro 2" keyboard and there is no ` aka. grave on it. Also there are no shortcuts on that keyboard to make a grave. We checked it on the keyboards official website. Thats why he is not able to open up the morph menu and change his identity. Is there any other way to open up that menu? Please help us.

**Comment by James103** [comment]
You can try changing the keybinds in the config.

**Comment by TBXYT** [comment]
Can you tell me how that works? Because we play on an survival multiplayer server, which means that i downloaded the mod on the server aswell.

**Comment by James103** [comment]
Actually, if you are using the latest version of Identity, the relevant settings are here:
![image](https://user-images.githubusercontent.com/37945304/105389554-91fb5600-5bdd-11eb-9e26-d12fcafefef0.png)

**Comment by TBXYT** [comment]
im using the latest one for 1.16.4 its called: identity-1.11.3-beta-1.16.4

**Comment by James103** [comment]
That's the same as what I have, which is where the controls screen is coming from.

**Comment by TBXYT** [comment]
thank you alot. It worked we changed it :) i will close the issue.
