### ISSUE TITLE
multiplayer issue

### ISSUE THREAD

**Issue by dumbcuck** [Draylar/identity#119]
when i use the ender dragon's ability on a multiplayer server that i made it disconnects me from the server

**Comment by James103** [comment]
Do you have the log? If so, can you post it here? (Don't try using Hastebin as it returns HTTP 503 when saving or loading)

**Comment by dumbcuck** [comment]
![image](https://user-images.githubusercontent.com/68575774/105555935-ffcb7e80-5cbe-11eb-8748-87105eee62e5.png)

**Comment by dumbcuck** [comment]
it still works on singleplayer

**Comment by dumbcuck** [comment]
help

**Comment by Draylar** [comment]
you posted the issue 2 hours ago, please respect my time and be patient, I can only work so fast

**Comment by Draylar** [comment]
Fixed in 1.11.4.
