### ISSUE TITLE
Identity server error when joining vanilla server

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Draylar/identity#122]
**Bug description**
* Launched up with my mods + identity joined my network lobby which has a vanilla papermc hub server

**Game log:**
[latest.log](https://github.com/Draylar/identity/files/5860848/latest.log)

**Comment by James103** [comment]
Identity must be running on the client **and server** to function properly.

**Comment by SirOMGitsYOU** [comment]
> Identity must be running on the client **and server** to function properly.

no worries thanks.
