### ISSUE TITLE
Crashing on start up

### ISSUE THREAD

**Issue by Cozza101** [Draylar/identity#123]
My game crashes on startup with the crash message 
"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'identity'!
Exit Code: -1"
and I was wondering is there a way to fix

**Comment by James103** [comment]
Can you try with the following setup?
* Minecraft 1.16.4 (no earlier, no later)
* Fabric Loader (latest version)
* Fabric API (latest version)
* Identity 1.11.4
* No other mods besides the above

**Comment by Cozza101** [comment]
yes I have tryed with no mods beside identity with the latest version of fabric and fabric api and with the mod menu mod (i tryed it with this mod after just identity) but thank you for trying to help

**Comment by James103** [comment]
Can you try posting the logs you get from my suggested setup? Hint: Don't use hastebin, instead try paste.ee or post in the following format:
```
<details>

<summary> Game log </summary>

[Delete this line and add your game logs here]

</details>
```

**Comment by Draylar** [comment]
If you are still experiencing the same issue, feel free to re-open this. I assume the crash was the Fabric API screen API issue, which can be fixed by installing the newest version of Identity.
