### ISSUE TITLE
Screen crashes with latest Fabric API

### ISSUE THREAD

**Issue by Gamercat735** [Draylar/identity#126]
I just tried to use the mod for the first time and the ´ (transform) key did not work. my game just freezes and then crashes. Everything else looks fine.
here is the crash report:
[crash-2021-01-27_14.46.33-client.txt](https://github.com/Draylar/identity/files/5883334/crash-2021-01-27_14.46.33-client.txt)

**Comment by James103** [comment]
Have you tried removing Identity and restarting the game? If it crashes then, could you post that crash report?

**Comment by Gamercat735** [comment]
i removed Identity and my game hasn't crashed

**Comment by James103** [comment]
Have you tried updating the following:
* Minecraft to **1.16.4** (not 1.16.5)
* Identity to 1.11.4
* Fabric API to latest available version
* Fabric loader to latest available version

Restart the game after updating the mods as shown above. If it crashes then, can you post the crash report?

**Comment by programmer2514** [comment]
I had the issue and I fixed it by downgrading to Fabric API v0.29.4

**Comment by Gamercat735** [comment]
> Fabric API v0.29.4

thanks for the help, my Identity is working just fine now

**Comment by Draylar** [comment]
Seems Fabric API has a new something-something for screens that requires modded screens to call a certain method. I'm going to keep this issue open so I fix it in the next update. Thank you for the report!

**Comment by Draylar** [comment]
Fully fixed in 1.11.5.

**Comment by James103** [comment]
Is this issue still worthy of being pinned? Identity 1.11 series is 4 versions (5 months) out of date as of the time of writing.
