### ISSUE TITLE
It used to work fine but after a power outage it started crashing!

### ISSUE THREAD

**Issue by DuckZGamer9122** [Draylar/identity#127]
The mod was working A-okay and now it just crashes! I did nothing out of the ordinary I just played it alongside other mods that was on a private server. After a power outage the mod started to crash my game.

**Comment by Draylar** [comment]
Please provide your game log through a service like [pastebin](https://pastebin.com/).

**Comment by Draylar** [comment]
Feel free to re-open this issue if you are still crashing.
