### ISSUE TITLE
Game Crashes when open Morph menu

### ISSUE THREAD

**Issue by Slimey127** [Draylar/identity#128]
crash-2021-01-28_18.39.21-client (1).txt
![crash](https://user-images.githubusercontent.com/78170484/106181826-598be700-619e-11eb-9698-f044e6f83fe2.jpg)
That is the crash log
and here 

https://user-images.githubusercontent.com/78170484/106182308-f2226700-619e-11eb-964e-14e1f84487fc.mp4

**Comment by James103** [comment]
You should find a crash report with filename in the form `crash-2021-01-28-...txt`. Can you post that crash report here?
In folder: `%APPDATA%\.minecraft\crash-reports`

**Comment by Slimey127** [comment]
Here it is
[crash-2021-01-28_18.39.21-client (1).txt](https://github.com/Draylar/identity/files/5889353/crash-2021-01-28_18.39.21-client.1.txt)

**Comment by James103** [comment]
Can you try downgrading Fabric API to v0.29.4 (no later, no earlier) and seeing if it crashes when opening the morph menu?

**Comment by Draylar** [comment]
#126, downgrade Fabric API as James said until a fix is released. Thanks for the report!
