### ISSUE TITLE
Typo in foxesAttackIdentityPrey description

### ISSUE THREAD

**Issue by James103** [Draylar/identity#13]
Minecraft 1.16.1
Fabric 0.8.8+build.202
LWJGL 3.2.2
Fabric API 0.14.0+build.371-1.16
Identity 1.1.0-beta-1.16 (a1e88372e58dba4cc6a967b77310082f9208d041)

The description for `foxesAttackIdentityPrey` currently says this:
> Whether Wolves will attack Players with an identity that the Wolf would normally hunt (Fish, Chicken).

This should be changed to this (bold = changed):
> Whether **Foxes** will attack Players with an identity that the **Fox** would normally hunt (Fish, Chicken).

**Comment by Draylar** [comment]
Fixed in 1.2.0, thanks!
