### ISSUE TITLE
Piglin Brutes attack you, even when you're morphed.

### ISSUE THREAD

**Issue by JoseBlackYT** [Draylar/identity#131]
Hello! I've come to a sort of "issue"? I've morphed into a piglin brute many times, no piglins attack me, instead the piglin brutes do! Please fix that.

**Comment by Draylar** [comment]
I'm fixing this in the next update with a rudimentary overwrite on the targeting portion of the Piglin Brute Brain AI. Hopefully, nobody does the same anytime soon! 😰
