### ISSUE TITLE
Mob effects.

### ISSUE THREAD

**Issue by nekomena20** [Draylar/identity#135]
The Wither Skeleton identity doesn't give the wither effect on contact with another mob. The Cave Spider doesn't give the poison effect on contact with another mob. The Husk doesn't give the Hunger effect on contact with another entity.  I'm rather curious as to why? If you do read this, I also think it could be a cool addition?

**Comment by Draylar** [comment]
The "why" is that I simply haven't implemented it yet (☞ﾟヮﾟ)☞

There's a discussion on this [here](https://github.com/Draylar/identity/discussions/91). It basically stems down to whether mob attacks should override tools. I'm currently leaning towards the idea that mob effects/damage will only apply when you attack with an empty hand, but weapons (swords) still work if you hold them. Let me know if you have any thoughts on that; might look into getting this out this weekend.

**Comment by Draylar** [comment]
A simple implementation of this is out in the next release~

**Comment by nekomena20** [comment]
It'd certainly be cool! I'd love seeing how it'd work. I think with stuff
like a wither skeleton, the damage of a sword, for example, stone + the
wither effect might make sense as the skeletons carry the weapon naturally.
But I'm totally down for that either way!
