### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Jake2134** [Draylar/identity#136]
It keeps crashing!!!! D:
Idk why
I have screenshot of crash
I am using fabric loader 1.16.4...
![dgfhrtfjhde](https://user-images.githubusercontent.com/57684951/107121532-092d1d00-6861-11eb-8084-e160c5a249a1.png)

**Comment by James103** [comment]
Do you have the full crash report and/or game logs? If so, can you post it via Pastebin or Github Gist?

**Comment by Draylar** [comment]
Going to take a stab in the dark and say this is probably the screen API crash. Try updating Identity to >=1.11.5 if you are on a lower version. If you are already on that version or it still crashes, please refer to James' comment.

**Comment by Jake2134** [comment]
> Do you have the full crash report and/or game logs? If so, can you post it via Pastebin or Github Gist?
nvm I found what was wrong :)
I had the wrong version of the fabric loader! xd

**Comment by Jake2134** [comment]
nvm I found what was wrong :)
I had the wrong version of the fabric loader! xd
It works fine now that I got the right version 👍
