### ISSUE TITLE
ability for the pillager

### ISSUE THREAD

**Issue by Rissman** [Draylar/identity#14]
Hi, make the ability for the pillager to sit and control on the ravager please!

**Comment by James103** [comment]
Same for evoker (both jockeys appear in raids). In other words, both pillagers and evokers should be able to ride and control ravagers.

**Comment by Draylar** [comment]
Pillagers and Evokers can now ride Ravagers in the next update 👍

**Comment by James103** [comment]
Did you mean "Pillagers, Evokers, and Vindicators" (as all three jockeys can spawn in raids)?
