### ISSUE TITLE
Can't join servers

### ISSUE THREAD

**Issue by xXKasmaXx** [Draylar/identity#144]
You can't join servers which don't have the mod so you probably have to restart mc with and without the mod all the time.
It says:
                    Connection lost
Incomplete set of tags received from the server.
          Please contact server operator.

**Comment by Draylar** [comment]
Identity is required on the client and server. Just like many other mods that add content, you will have to disable the mod to join a vanilla server. The tag issue is a game limitation and outside my control.

To separate your game profiles and avoid having to switch out mods when you visit different servers, I would recommend using MultiMC.
