### ISSUE TITLE
Critical Error upon 1.16.5 instance's first launch [MultiMC]

### ISSUE THREAD

**Issue by Bunistalri** [Draylar/identity#145]
**Bug description**

Identity Version: 1.11.6-beta-1.16.4
Fabric Version: 0.11.1 (release)

What was expected to happen: The new 1.16.5 MultiMC instance launching successfully and working fine when creating single/multiplayer worlds.

What actually happened: 
Got a Fabric Loader error window. Beyond the Fabric Loader error window, nothing else launched. Then found a critical error in the MultiMC console log. The critical error can be found in the pastebin below.

The Fabric loader error window states:
Failed to launch!
❌ Could not find required mod: identity requires {fabric @ [*]}
|
—❌ Creating empty clause ?

Other mods (probably aren't the cause but will be included anyways): 
Voxelmap (Fabric) 1.10.15 (for 1.16.5)

**Game log:**
Here's the pastebin log since I have no idea how to use hastebin. 
https://pastebin.com/iCbPCGDP

**Comment by James103** [comment]
Can you please install Fabric API? Use version 0.29.4 if you are not on the latest version of Identity, or use 0.30+ otherwise.

**Comment by Bunistalri** [comment]
Oh. I think that may have worked! :0

Here's a new pastebin of the log after chucking Fabric API 0.30.3+1.16 in the Mods folder, re-launching successfully, making a new world, and er, making some mobs _liven't_. There are some warnings but no more errors: https://pastebin.com/Z9XXmtuq

**Comment by Bunistalri** [comment]
Yeah, everything seems to be working fine now. Whoops, sorry about that. Thanks y'all! Feel free to close the issue!

**Comment by Draylar** [comment]
Thank you for using the bug report format properly (and thanks for the help, as usual, James)! I wish every report was as detailed as yours, haha
