### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by YuriiDZN** [Draylar/identity#146]
Game keep crashing when trying to open the menu
When i use the key for opening the menu, it crash instantly

The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: com.mojang.blaze3d.systems.RenderSystem.enableScissor(IIII)V
Code de sortie : -1

https://pastebin.com/WcjcrW1K

**Comment by James103** [comment]
Can you please update Minecraft to 1.16.4, then retry? If it still crashes, can you post that crash log here?
