### ISSUE TITLE
Pehkui incompatibility

### ISSUE THREAD

**Issue by deltanedas** [Draylar/identity#148]
**Bug description:**
Pekhui has mixins that collide with Identity.

**Game log:**
[here](https://paste.gg/p/anonymous/a10a273ba06344a98060fddabaebe972),
- spammed when creating a world
- crashing when loading an existing one.

**Extra info:**
Using Sodium, Lithium, Hydrogen, Starlight, BiomesYoullGo (generator being used), Pekhui.
Fabric Loader 0.11.1 for 1.16.5.

To reproduce this simply create a world.

**Comment by Draylar** [comment]
Update Pehkui to the 1.17 version.
