### ISSUE TITLE
Pufferfish attack crashes the game

### ISSUE THREAD

**Issue by Ch1216** [Draylar/identity#149]
I attacked a mob as a pufferfish and the game crash
I thought it would not crash, An with the new update maybe inflict poison

I don't know how to use hastebin I'm trying to save it but nothing happens so i cant give a game log

However The launcher gave me this: 
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.attack_damage
Exit Code: -1

**Comment by Draylar** [comment]
Wow, good catch! Didn't think to test mobs _without_ special attack mechanics. This should be fixed in 1.11.8 (out in a second), please let me know if you encounter any other issues. Thank you for the report!

**Comment by DomMOW** [comment]
#

> Wow, good catch! Didn't think to test mobs _without_ special attack mechanics. This should be fixed in 1.11.8 (out in a second), please let me know if you encounter any other issues. Thank you for the report!

How did you actually fix this issue?

**Comment by James103** [comment]
> How did you actually fix this issue?

Likely fixed in 3c68390e6d9a9baf42d52029593e31368b75b1a6

**Comment by DomMOW** [comment]
> > How did you actually fix this issue?
> 
> Likely fixed in [3c68390](https://github.com/Draylar/identity/commit/3c68390e6d9a9baf42d52029593e31368b75b1a6)

I can't see a way this could fix my mod issue, damn. Thanks for helping
