### ISSUE TITLE
Not able to launch

### ISSUE THREAD

**Issue by TotalNotDog** [Draylar/identity#152]
I load in with Fabric on 1.16.2 and get this: Could not find required mod: identity requires {fabric @ [*]}
Please respond!

**Comment by James103** [comment]
Have you tried updating Identity to 1.11.8, Minecraft to 1.16.4, and Fabric API to 0.30 or later?

**Comment by Draylar** [comment]
As James said, Identity does not support versions below 1.16.4. If you want to play on 1.16.2, you will have to find an older jar (probably around [this date](https://www.curseforge.com/minecraft/mc-mods/identity/files/3124852)). If you are still having trouble, feel free to reopen this issue with your full game log uploaded to a service like [pastebin](https://pastebin.com/).
