### ISSUE TITLE
Immersive Portals Incompatibility

### ISSUE THREAD

**Issue by srnyx** [Draylar/identity#157]
**Bug description**
The game crashed when trying to use the Ender Dragon ability

**Game log:**
https://pastebin.com/LpZ7mhQM

**Comment by Draylar** [comment]
This seems like a "not my fault" issue, but I'm happy to do whatever changes are needed if the author of the other mod disagrees.

**Comment by qouteall** [comment]
Seems that it's not "not your fault". Identity spawns entity in networking thread and it may cause concurrency issues. The packet should be handled in the server thread (using MinecraftServer.execute). IP just does the thread check

**Comment by Draylar** [comment]
That's an odd thing to brick the game over, but I'll look into patching it on my side in the next update.
