### ISSUE TITLE
Players aren't seeing my identity

### ISSUE THREAD

**Issue by zombies134** [Draylar/identity#164]
Other players see me as a regular player and not as my chosen identity.

**Comment by Draylar** [comment]
Do you have the mod installed on the server **and** all clients? Please provide your server and client game logs through [pastebin](https://pastebin.com/).

**Comment by zombies134** [comment]
> 
> 
> Do you have the mod installed on the server **and** all clients? Please provide your server and client game logs through [pastebin](https://pastebin.com/).

I just checked, turns out I forgot to install it on the server, sorry for taking so long to respond.
