### ISSUE TITLE
Undead Identities aren't healed by Instant Damage and vice versa

### ISSUE THREAD

**Issue by James103** [Draylar/identity#17]
Minecraft 1.16.1
Fabric 0.8.8+build.202
LWJGL 3.2.2
Fabric API 0.14.0+build.371-1.16
Identity 1.2.0-beta-1.16

When you are disguised as any undead mob and you gain the Instant Damage effect, you are still damaged, unlike actual undead mobs which are instead healed. The Instant Health effect still heals you even when you are undead, even though it's supposed to damage you in this specific case.

**Comment by Draylar** [comment]
Fixed in 1.3.0.
