### ISSUE TITLE
Command Blocks can't turn you in to anything

### ISSUE THREAD

**Issue by SparkyTheDoggo** [Draylar/identity#171]
I was messing around in Minecraft to see everything the mod could do when I noticed their are commands to make it work as well, and I tested them, they work fine, but when I put that exact same command in a Command Block it no longer worked

**Comment by James103** [comment]
What output do you get inside the command block upon running the `/identity equip` commands?

**Comment by SparkyTheDoggo** [comment]
> What output do you get inside the command block upon running the `/identity equip` commands?

it says "A player is required to run this command here"

**Comment by James103** [comment]
What output do you get for running each of these 2 commands in a command block?
`identity equip @p zombie`
`execute as @p run identity equip @s zombie`

**Comment by SparkyTheDoggo** [comment]
> What output do you get for running each of these 2 commands in a command block?
> `identity equip @p zombie`
> `execute as @p run identity equip @s zombie`

The first one has the same output but the second one worked!
