### ISSUE TITLE
Game refuses to even load the mod on servers

### ISSUE THREAD

**Issue by StereoMadnessss** [Draylar/identity#173]
When I am using the mod, the game runs fine. Then after a while I realized that the mod does not work on servers. When trying to join a server with the identity mod it says "Incomplete set of tags recieved from server. Please contact server operator." I don't know it has to do with my device, but it is most likely that the identity mod is not compatible with multiplayer servers. In the future I would like to see the mod be compatible with servers.

**Comment by codegavran** [comment]
Does the server you're trying to connect to run the mod?

**Comment by StereoMadnessss** [comment]
No

**Comment by StereoMadnessss** [comment]
I think it does not run the mod so it does not work
