### ISSUE TITLE
Mod crashing server instantly. Works in singleplayer.

### ISSUE THREAD

**Issue by xBogdy** [Draylar/identity#180]
Hi. I have made a few small changes to the mod to morph randomly every minute. And it worked fine in single-player but multiplayer doesn't work at all. The server crashes as soon as I join. The unchanged mod works fine, I hope it is okay to ask for help about this kind of stuff.

I use fabric-API-0.30.0

Here is the modification I made which causes the server to crash.

I added 2 functions to run on every tick
![image](https://user-images.githubusercontent.com/62604613/113933724-9b1fba80-97fd-11eb-8627-700d3c654ed5.png)

These are the two classes where I made changes:
https://github.com/xBogdy/minecraftMods/blob/75aa4bf248a4a8e83e5df00a164aa42aa8d118c4/src/main/java/draylar/identity/screen/widget/EntityWidget.java#L54

https://github.com/xBogdy/minecraftMods/blob/master/src/main/java/draylar/identity/cca/IdentityComponent.java

This is the server's crash report:
[crash-2021-04-08_00.08.01-server.txt](https://github.com/Draylar/identity/files/6274518/crash-2021-04-08_00.08.01-server.txt)
                             and log:
[latest.log](https://github.com/Draylar/identity/files/6274523/latest.log)
[2021-04-07-6.log.gz](https://github.com/Draylar/identity/files/6274524/2021-04-07-6.log.gz)

I'd greatly appreciate your help

**Comment by Draylar** [comment]
You put your server utility methods inside a client-side class, hence the `NoClassDefFoundError`. 

If you need random auto-swapping behavior, I just pushed the [autoswap](https://github.com/Draylar/identity/tree/autoswap) branch, which was made a month or two ago for some video content. You can build that branch for [swap every minute/swap every day/swap on damage] functionality and edit the new config options (for toggling functionality) or modify the code if you need additional changes.
