### ISSUE TITLE
exp doesn't adds when morph - possible EnchantPlus incompatibility

### ISSUE THREAD

**Issue by JoakoLP** [Draylar/identity#185]
I'm playing in a modded server and I thought that the problem was [EnchantPlus](https://www.curseforge.com/minecraft/mc-mods/enchantsplus). But now I'm not pretty sure. Just in case, I post the problem on both sides.
The problem is that when I use a fortune IV or more(added by EnchantPlus) and I break a Vain, the exp doesn't add to the player. But if I morph back to human, it does.

**Comment by JoakoLP** [comment]
I've looking it around and I think that the mending enchantment is doing this problem

**Comment by Draylar** [comment]
Don't think this is Identity-- I don't touch experience at all. EnchantPlus is ARR so it is not possible for me to view what they are doing. Feel free to re-open if needed.
