### ISSUE TITLE
Suggestion: /identity command to manage player's Identities

### ISSUE THREAD

**Issue by James103** [Draylar/identity#19]
This command is used to manage a player's Identities.

### Syntax
`identity grant <player> <entity>`
`identity revoke <player> <entity>`
`identity equip <player> <entity>`
`identity unequip <player>`
`identity test <player> [not] <entity>`

### Arguments
`<player>`: Specify a player to give/revoke/equip an Identity to.
`<entity>`: Specify the Identity that should be given/revoked/equipped.

### Result
Fails if the arguments are invalid, if `<player>` fails to resolve to an online player, or if nothing changed when performing the command.

On success:
* `identity grant <player> <entity>`: Grants the specified identity to the specified player.
* `identity revoke <player> <entity>`: Revokes the specified identity from the specified player.
* `identity equip <player> <entity>`: Makes the specified player change to the specified identity.
* `identity unequip <player>`: Makes the specified player unequip any currently equipped Identity.
* `identity test <player> [not] <entity>`: Tests whether the player is currently (not) disguised as the specified entity.

### Examples
* All players get the ability to turn into a Skeleton: `execute as @a run identity grant @s minecraft:skeleton`
* You can no longer turn into a Giant: `identity revoke @p minecraft:giant`
* All players become Zombies: `execute as @a run identity equip @s minecraft:zombie`
* You unequip your current Identity: `identity unequip @p`
* Check whether you are not a Pig: `identity test @p not minecraft:pig`

**Comment by Draylar** [comment]
Implemented in 1.4.0 (basically to spec, with the only difference being modified test syntax), thanks for the detailed suggestion!
