### ISSUE TITLE
Can't load up the mod without the game crashing

### ISSUE THREAD

**Issue by EmacSans** [Draylar/identity#191]
**Bug description**
The only thing that happens is the game takes too long to load and then crashes with the game crash saying something failed to load like Error: java.lang.NoClassDefFoundError: Could not initialize class draylar.identity.registry.Components.

**Game log:**
*I have no clue how to use hastebin
[Crash Log.txt](https://github.com/Draylar/identity/files/6410734/Crash.Log.txt)
*

**Comment by MimzyFang** [comment]
same issue on mc servers

**Comment by MimzyFang** [comment]
this seems to be an issue with pehkui

**Comment by Draylar** [comment]
Yes, this is an issue between Pehkui & Identity. I think their compatibility assumes an older version of CCA is present, and because I moved up to the new system, it is now breaking... or something like that.

**Comment by superon** [comment]
wish i'd seen this 4 hours ago, been trying to find out what was going on for about 12 hours \o/  previous version still works just fine (1.12.0) kinda hilarious though when you consider this was first version listed as [stable] :P

**Comment by MimzyFang** [comment]
This has been fixed now
