### ISSUE TITLE
Won't load

### ISSUE THREAD

**Issue by Antram1** [Draylar/identity#192]
When I try to create a world or join one, it stops before 10% and just doesn't continue loading. I can't close the game without using the task manager.
![Minecraft_ 1 16 5 2021-05-02 17_40_50](https://user-images.githubusercontent.com/83546976/116818839-4f92cf00-ab65-11eb-9ad1-00e2104a8acf.png)

**Comment by James103** [comment]
Can you please post the resulting `latest.log` (game log output)?

If you are using MultiMC, from the launcher, you can do the following:
1. Right click on the instance icon and select "Edit Instance".
2. In the edit instance window, select "Minecraft Log".
3. Click "Upload".
4. Post the resulting paste.ee link here.

**Comment by MimzyFang** [comment]
this seems to be an issue with pehkui

**Comment by StormA7** [comment]
Like I have the same issue I don't know if its ram but like I give 5 gigs and still does not load and I have to completely restart my computer just to close the game!

**Comment by MimzyFang** [comment]
there is an issue with fabric api 34 and Pehkui
see #197 & #191 for reference

**Comment by Draylar** [comment]
CCA issues are fixed in 1.13.1. If you are using Pehkui, update it to the latest fix release.
