### ISSUE TITLE
My friends can't see me morphed

### ISSUE THREAD

**Issue by Sage456123** [Draylar/identity#193]
**Bug description**
*When I add this in my aternos server and I try to play in it by morphing, My friends can'tsee me morphed as anything, They just see me as normal character but when they hit me, They says I tak out of the sound I am morphed in.*

**Game log:**
*Upload your game log through [hastebin](https://hastebin.com/) and provide the link. Do not paste the link directly into the submission box or comments.*

**Comment by James103** [comment]
Do you have the mod installed on the client side as well? Identity must be installed on both server **and client** to function properly.

**Comment by Sage456123** [comment]
> server

Yes I have!

**Comment by James103** [comment]
Can you please copy the logs for your server found at `https://aternos.org/log/` and paste them here (using https://paste.ee/, https://hastebin.com/)?

If the log says `Log was cleared, because it was too big.`, can you please restart the server and try reproducing the issue, the attaching the resulting logs?

**Comment by Sage456123** [comment]
> Can you please copy the logs for your server found at `https://aternos.org/log/` and paste them here (using https://paste.ee/, https://hastebin.com/)?
> 
> If the log says `Log was cleared, because it was too big.`, can you please restart the server and try reproducing the issue, the attaching the resulting logs?

Can I add you to discord pls?

**Comment by Draylar** [comment]
You will have to find an alternative to Aternos for server hosting. They mess with something (I don't know what), and this mod has failed to work with them since day 1. 

edit: feel free to continue debugging here, of course, but Aternos as a server provider will most likely not work.

**Comment by Draylar** [comment]
![image](https://user-images.githubusercontent.com/17728338/116824032-9aa0e800-ab4d-11eb-9f8d-edecfc6bd0e5.png)

**Comment by Sage456123** [comment]
What do I do now then??

**Comment by Draylar** [comment]
>You will have to find an alternative to Aternos for server hosting.

**Comment by Sage456123** [comment]
> > You will have to find an alternative to Aternos for server hosting.

How?? PLEASE HELP ME

**Comment by Draylar** [comment]
You can [purchase a server](https://extravm.com/) or [forward a port yourself](https://www.youtube.com/watch?v=pSEhgCp5UBk). Another option would be contacting Aternos support to see if they can help you.

**Comment by Sage456123** [comment]
> You can [purchase a server](https://extravm.com/) or [forward a port yourself](https://www.youtube.com/watch?v=pSEhgCp5UBk). Another option would be contacting Aternos support to see if they can help you.

Can I use ploudos?

**Comment by Draylar** [comment]
> ploudos

I haven't heard of Pludos before, so I do not know. Doesn't hurt to try.

**Comment by Sage456123** [comment]
> > ploudos
> 
> I haven't heard of Pludos before, so I do not know. Doesn't hurt to try.

Do you have any more idea then buying a new server?

**Comment by Draylar** [comment]
The only other option is forwarding a port yourself.

**Comment by Sage456123** [comment]
> The only other option is forwarding a port yourself.

Can you tell me like the steps please? I only download Fabric Api and the mod, I have to install fabric mod loader to make it work?

**Comment by Fauli1221** [comment]
Do you have access to your router?

**Comment by MimzyFang** [comment]
> > The only other option is forwarding a port yourself.
> 
> Can you tell me like the steps please? I only download Fabric Api and the mod, I have to install fabric mod loader to make it work?

Do you have access to your router?

**Comment by MimzyFang** [comment]
> > The only other option is forwarding a port yourself.
> 
> Can you tell me like the steps please? I only download Fabric Api and the mod, I have to install fabric mod loader to make it work?

And yes you need fabric Mod Loader without that non fabric Mod will work. You can get it from https://fabricmc.net/use/ just install it like forge

Or alternatively I can recommend installing MultiMC it makes it relatively easy to install fabric if you need any help just ask
