### ISSUE TITLE
Identity wont work with minecraft.

### ISSUE THREAD

**Issue by whyyousorude0** [Draylar/identity#201]
**Bug description**
*A description of what you expected to happen and what actually happened.*

**Game log:**
*Upload your game log through [hastebin](https://hastebin.com/) and provide the link. Do not paste the link directly into the submission box or comments.*

**Comment by whyyousorude0** [comment]
Everytime I make a world, when it's in the loading thing, it just crashes.
[crash file.txt](https://github.com/Draylar/identity/files/6437422/crash.file.txt)

**Comment by whyyousorude0** [comment]
I tried downgrading the identity and fabric API and it would now just sit there in place.
![Capture](https://user-images.githubusercontent.com/83787538/117361019-7a439700-ae87-11eb-995b-67ab977bb6dc.PNG)

**Comment by MimzyFang** [comment]
Use fabric api 33

**Comment by Fauli1221** [comment]
Duplicate of #198

**Comment by Valdejan** [comment]
api 33 doesn't fix this problem

**Comment by whyyousorude0** [comment]
so what fixes it?

**Comment by whyyousorude0** [comment]
figured it out actually. use 1.16.3 (identity version 1.9.1) with fabric api 0.32.0

**Comment by whyyousorude0** [comment]
Issue has been closed. Thanks for trying to help.

**Comment by whyyousorude0** [comment]
If it continues to mess up I'll reopen this.

**Comment by Draylar** [comment]
CCA/FAPI issues should be fixed in 1.13.1, which will be released in a second.

**Comment by Valdejan** [comment]
Soon?
