### ISSUE TITLE
1.13.1 still crashing

### ISSUE THREAD

**Issue by Valdejan** [Draylar/identity#202]
When working with Pehkui this mod continues to freeze loading into a world. I've tried a lot of things, and duh I used older versions, but im trying to get 1.13 or 1.13.1 to work with Pehkui

**Comment by Draylar** [comment]
post game logs

**Comment by Valdejan** [comment]
Steps

**Comment by MimzyFang** [comment]
Did you update Pehkui

**Comment by ghost** [comment]
Identity crash / pehkui last update and still crashing;

https://pastebin.com/CA3RySLH

**Comment by Draylar** [comment]
PRing a fix to Pehkui now. In the meantime, you can get an updated jar from https://github.com/Draylar/Pehkui/releases/tag/2.1.1-21w18a (confirmed working with identity 13.1 in vanilla). Thanks for the report.
