### ISSUE TITLE
Game crashes/freezes

### ISSUE THREAD

**Issue by Ch1216** [Draylar/identity#204]
When I load a world sometimes it freezes/crashes NOTE: Some specific worlds freeze rather than crash
I expected to it not crash or freeze

**Game log:**
Cant use pastebin as it doesn't work for me, 

[latest.log](https://github.com/Draylar/identity/files/6445027/latest.log)
This is the log for a world that just freezes

[crash-2021-05-07_22.28.00-server.txt](https://github.com/Draylar/identity/files/6445030/crash-2021-05-07_22.28.00-server.txt)
Crash when I load a world for the first time

[crash-2021-05-07_22.37.44-server.txt](https://github.com/Draylar/identity/files/6445033/crash-2021-05-07_22.37.44-server.txt)
Crash when I load a world for the second time

**Comment by James103** [comment]
Can you please try downgrading Fabric API to 0.33.x, then restarting the game?

**Comment by Ch1216** [comment]
> Can you please try downgrading Fabric API to 0.33.x, then restarting the game?

Nvm, I found draylars pehkui it fixed it for me
