### ISSUE TITLE
mod crashing

### ISSUE THREAD

**Issue by XdPurple** [Draylar/identity#208]
Hello i want to play this mod with my mod pack but it just keeps crashing                                                                                                                  The game crashed whilst feature placement
Error: dev.onyxstudios.cca.internal.base.asm.StaticComponentLoadingException: Exception while registering static component factories for Identity (identity)
Exit Code: -1
[crash-2021-05-09_01.16.33-server.txt](https://github.com/Draylar/identity/files/6446971/crash-2021-05-09_01.16.33-server.txt)

**Comment by Draylar** [comment]
#203
