### ISSUE TITLE
Mob Transformation List Doesn't Show! Whenever I search something up, my game crashes. Help?

### ISSUE THREAD

**Issue by LoadSystem** [Draylar/identity#210]
**Bug description**
*A description of what you expected to happen and what actually happened.*
![image_2021-05-11_091920](https://user-images.githubusercontent.com/84034212/117850241-f815f280-b239-11eb-8125-fa3778259c31.png)

**Game log:**
*Upload your game log through [hastebin](https://hastebin.com/) and provide the link. Do not paste the link directly into the submission box or comments.*

**Comment by Draylar** [comment]
As the template mentions in your post, I need a game log. Hastebin is down, so you can opt for an alternative such as [pastebin](https://pastebin.com/).

**Comment by adroslice** [comment]
Same apparent issue here, here's my log:
https://pastebin.com/qbuqWUJj

**Comment by Draylar** [comment]
Great catch, thanks for the report! Scrolling when you haven't unlocked anything will crash the game.
