### ISSUE TITLE
Error with identity mod on my server

### ISSUE THREAD

**Issue by Sage456123** [Draylar/identity#212]
So I installed Identity Mod in my server(Aternos and server.jar), When I install the mod in aternos, My morph is not visible to others and their morph is not visible for me but when I install the mod in server.jar it says "incomplete set of tags received from server" Please help me, I really want to play identity mod with my friends.

**Comment by James103** [comment]
Can you try setting up a local server or using a different service to host your modded server with Identity. Aternos is known for breaking several mods, including Identity.

**Comment by Sage456123** [comment]
> Can you try setting up a local server or using a different service to host your modded server with Identity. Aternos is known for breaking several mods, including Identity.

Like what? I want to make a server for cracked players becoz me and my friends are poor!

**Comment by Draylar** [comment]
As I mentioned a few times before in your other issues, Aternos is not supported by Identity. `incomplete set of tags received from server` generally means your server was not properly installed, or the Identity mod is not installed on one side. While I will not stop other people from chiming in to help on this issue, this bug tracker is not the appropriate place to ask for server setup support. Try asking in the Fabric Discord #player-support channel, where there are players who deal with issues like these frequently.

**Comment by Sage456123** [comment]
> As I mentioned a few times before in your other issues, Aternos is not supported by Identity. `incomplete set of tags received from server` generally means your server was not properly installed, or the Identity mod is not installed on one side. While I will not stop other people from chiming in to help on this issue, this bug tracker is not the appropriate place to ask for server setup support. Try asking in the Fabric Discord #player-support channel, where there are players who deal with issues like these frequently.

Do you know any other server creater that creates a server for free and for cracked users?
