### ISSUE TITLE
Start up

### ISSUE THREAD

**Issue by bigdongvic** [Draylar/identity#213]
After I start up Minecraft through the launcher it gives me a warning when and it reads- "File identity-1.13.1-1.16.5-jar is a fabric mod and can't be loaded." I don't know what to do can anyone help?

**Comment by Draylar** [comment]
Identity is a Fabric mod, but you have Forge installed. You can read through the [Fabric wiki tutorial](https://fabricmc.net/wiki/install) for installation details in all launchers.
