### ISSUE TITLE
Iron Golem

### ISSUE THREAD

**Issue by Sage456123** [Draylar/identity#216]
So Its crazy that you added hands. But when I even like hit a entity with iron golem. The hand starts to swing and never stops, Can you please fix this?

**Comment by JoseBlackYT** [comment]
Same thing happens with the ravager.

**Comment by LightblueStar27** [comment]
And the creeper

**Comment by FurtherSecrets24680** [comment]
This happened to me too!

**Comment by Draylar** [comment]
All 3 have been fixed in the next update, thanks for reporting!
