### ISSUE TITLE
server

### ISSUE THREAD

**Issue by B13D4R** [Draylar/identity#221]
Hello, when I installed the identity mod, it didn't work. yet when I kill a mob, it puts a identity mod thing where my inventory is. Can you make a server version?

**Comment by B13D4R** [comment]
IT says identity.unlock_entity

**Comment by Draylar** [comment]
Identity is required on the client **and** server, but it seems like you only have it on the server. If you do have Identity installed on both sides, please provide a client & server [game log](https://minecrafthopper.net/help/guides/getting-minecraft-launcher-log/).

**Comment by B13D4R** [comment]
no i tried that it givess error
