### ISSUE TITLE
So i was in a woodland mansion got attacked by. A zomebie didnt die still showed the u died screen i didnt even respawn is this an issue with identey or minecraft itseld

### ISSUE THREAD

**Issue by crystaltheshapeshifter** [Draylar/identity#225]
**Bug description**
*A description of what you expected to happen and what actually happened.*

**Game log:**
*Upload your game log through [hastebin](https://hastebin.com/) and provide the link. Do not paste the link directly into the submission box or comments.*

- [ ] and now my carecter I stuck in the death animation for a while.

**Comment by Draylar** [comment]
This was probably related to TPS issues, which should now be fixed. Let me know if you experience anything similar in the future.

**Comment by James103** [comment]
@crystaltheshapeshifter In the future, make sure to use a more concise title and put the description of the bug in the body and not the title.
