### ISSUE TITLE
Can't become an arctic fox

### ISSUE THREAD

**Issue by Zunkz** [Draylar/identity#227]
That's literally it I can't become one there isn't an option

**Comment by James103** [comment]
Likely a duplicate of #55

**Comment by Foxite** [comment]
I'm looking into this but it seems to require a major intervention into the code, as identities/abilities are stored by the class of the entity, and arctic foxes and red foxes are the same class.

This has also prevented me from adding a fox ability that is different depending on the fox type, so I'm considering this a high priority task on my personal schedule :grin:

**Comment by Draylar** [comment]
Done in 2.3.0!
