### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by TheNimbleNinja** [Draylar/identity#229]
**Bug description**
crash on startup

**Game log:**
https://gist.github.com/TheNimbleNinja/5567228ffc7ed9f64146c89bc25ea4de

**Comment by Draylar** [comment]
Do not think this is an Identity issue (not mentioned in the log, pretty sure I do not touch the mixin that is crashing). FallFlyingLib, which is probably conflicting with another mod, does not have a 1.17 jar, so I can't verify fully, but I can double-check once they publish one.

**Comment by Draylar** [comment]
I believe the other mod fixed it on their end, but I am fixing it on my end as well, so it should work either way in the next release.
