### ISSUE TITLE
Lag on Single Player

### ISSUE THREAD

**Issue by marcelopierry** [Draylar/identity#235]
When playing on single player 1.17 the game is extremely laggy. I will break blocks and they will take 2 extra seconds to actually break, mobs will move incredibly slowly, and there dead bodies will linger on the ground for a couple seconds after there death. For more information I have a 2080s graphics card and the intel i9-900ks cpu so my computer should not be the issue. I also gave the Fabric install 8g of Ram so it had way more than enough ram to run and I lowered all of Minecraft's video settings when playing the game so my computer could focus just on this mod. I also was only using this mod and nothing else (beside fabric api).

**Comment by James103** [comment]
1. Have you looked at the graphs that you get when you do Alt+F3 (most specifically the tick time on the bottom right corner)?
2. Press F3+L, then wait for 10 seconds. You should get a zip file within your Minecraft instance's `debug` folder and `profiling` subfolder. Can you please attach that zip file here?

**Comment by marcelopierry** [comment]
> 1. Have you looked at the graphs that you get when you do Alt+F3 (most specifically the tick time on the bottom right corner)?
> 2. Press F3+L, then wait for 10 seconds. You should get a zip file within your Minecraft instance's `debug` folder and `profiling` subfolder. Can you please attach that zip file here?

Okay I did what you asked and also made a recording of the issue. 

1. The F3 + L Zip File 
[2021-06-17_12_49_58-Axolotl Challenge-1_17.zip](https://github.com/Draylar/identity/files/6672863/2021-06-17_12_49_58-Axolotl.Challenge-1_17.zip)
2. A video showing the lag that I experience 
https://user-images.githubusercontent.com/76548876/122464270-841ee680-cf6b-11eb-8005-3680ddddcc08.mp4
3. Screen Shots with the pie chart and other tick info
![2021-06-17_12 48 19](https://user-images.githubusercontent.com/76548876/122464423-aadd1d00-cf6b-11eb-8630-a46d81ce6114.png)
![2021-06-17_12 49 15](https://user-images.githubusercontent.com/76548876/122464431-aca6e080-cf6b-11eb-8023-fdf54ee4d769.png)

Please let me know if you need any other info from me!

**Comment by Stealthii** [comment]
I can confirm that I get this lag on single player as well. However, running a Fabric server with this mod installed both server and client side, do not have this issue at present.

**Comment by Draylar** [comment]
I think my Angerable Patch library mod, which was designed to prevent log spamming due to a 1.16.5 error, was spamming the logs due to it not working in 1.17. 1.14.1 beta should fix this, but let me know if you still encounter the issue.
