### ISSUE TITLE
[1.17.x] Unlocked entities not synced on server connect

### ISSUE THREAD

**Issue by Stealthii** [Draylar/identity#239]
When rejoining a server in 1.17, unlocked Identities appear blank. Only when a new one has been unlocked does the server refresh this information to the client, and all previously unlocked, including the new are visible.

**Comment by Draylar** [comment]
I suspect this is related to the FPS drop/player corruption issue, so it should be fixed in 1.14.1 beta. I tested in a dedicated server with the update and everything seemed to work fine. Let me know if you encounter it again!

**Comment by Stealthii** [comment]
Semi-good news: this bug does not occur under normal client/server conditions (ie. direct connection).

When using Velocity as a proxy in front of the Fabric server running Identity, this issue will occur consistently. Even if Velocity is run with no plugins (such as ViaVersion, ViaBackwards, Geyser, Floodgate, which I'd expect to introduce issues) - so it's the first connection packet that seems to be throwing a spanner in the works.

I'll not re-raise this bug as it's not strictly a bug within Identity that causes this. However I'll look into the network connection code, and see if there's a more concrete way of delivering this information to the client even in proxy situations. If I find a workaround, I'll raise a PR for you.

Thanks for your continued work on this mod!
