### ISSUE TITLE
[1.17.x] Respawn attempt corrupted player data

### ISSUE THREAD

**Issue by Stealthii** [Draylar/identity#240]
**Bug description**
When I died with Enderman as my chosen identity, the server failed to execute a function on respawn. After disconnecting, I cannot reconnect as player data is corrupt.

Providing both game log and player data file. Restoring the '.dat_old' file allowed me to reconnect.

**Game log:**
Server failure on attempted respawn: https://hastebin.com/avafafuvoh.properties
Corrupted playerdata (and previous backup): https://consoletation.live/temp/identity-240-playerdata.zip

**Comment by Draylar** [comment]
This should be fixed in 1.14.1 beta, which will be out in a second. Please let me know if you encounter the issue again.

**Comment by Stealthii** [comment]
Put myself in this situation about 10 times, and the issue didn't reoccur. Thanks!
