### ISSUE TITLE
200-500ms ticks

### ISSUE THREAD

**Issue by skylorbeck** [Draylar/identity#242]
I have no idea what actually caused this but it was solved by removing this mod. After an hour or two, entities start to jitter and stutter and warp around due to massive tps drops. Persists through save/reload and is only fixed by complete restart.

**Comment by James103** [comment]
Try pressing F3+L (run `/tick warp 3600` beforehand if Carpet mod is installed), then waiting for 10 seconds. A zip file should be created in your Minecraft instance's `debug/profiling` folder. Attach this latest zip file here.

**Comment by Draylar** [comment]
Latest release (1.14.1) should probably solve this, otherwise follow the above steps ^^

**Comment by gazecube** [comment]
[2021-07-29_04_56_36-my serv-1_17.zip](https://github.com/Draylar/identity/files/6900566/2021-07-29_04_56_36-my.serv-1_17.zip)
Sorry about hijacking this, but I'm getting some serious TPS issues in my server when the mod's loaded and I'm loaded in.

**Comment by Draylar** [comment]
IIRC this was due to Angerable Patch spamming log files (which should be fixed now), but please let me know if you re-encounter the problem 👍
