### ISSUE TITLE
World crashes (1.17)

### ISSUE THREAD

**Issue by Ameliaplayz** [Draylar/identity#243]
**Bug description**
*So my world crashed and I'm using a mod called not enough crashes, it says that suspected mod issues are the identity mod*

**Game log:**
*https://hastebin.com/epohuxuyek.yaml*

**Comment by James103** [comment]
Does the game crash if you run `/identity revoke @s the_aether:aechor_plant` and `/gamemode survival` first, then bring up the Identity screen? The renderer for that specific entity type may be causing the crash.

**Comment by Ameliaplayz** [comment]
i don't think so, the time that it happened was when I visited the aether, and then it crashed

**Comment by Ameliaplayz** [comment]
it was on creative because of testing 1.17
