### ISSUE TITLE
Crash after using Ghast abilities

### ISSUE THREAD

**Issue by Ectalite** [Draylar/identity#25]
I'm playing on a self hosted server with the modpack All of Fabric which contains Identity.
After using the Ghast abilities, the server crashed and we got the following crash report: [Paste.ee link](https://paste.ee/p/HnBoL).

We also saw that the GUI was completely broken:
![image](https://user-images.githubusercontent.com/31344054/88474994-461c6c80-cf2c-11ea-9915-a338d3f97b01.png)

**Comment by James103** [comment]
Are you able to reproduce the same crash with the NotEnoughCrashes mod? If so, could you send the resulting crash report? The deobfuscated stack trace may help.

**Comment by Draylar** [comment]
It's ok Jamie, I have a tool for mapping the log, but thanks for asking. Will look into this tonight.

**Comment by sean-work** [comment]
I have narrowed down the conflict here. #26

**Comment by Draylar** [comment]
Going to assume these issues were fixed from dep updates in 1.5 (as #26, with same issues, was fixed due to them). Let me know if the Ghast issues still persist.
