### ISSUE TITLE
Author, please make evoker's skills

### ISSUE THREAD

**Issue by kridb** [Draylar/identity#253]
**Bug description**
*A description of what you expected to happen and what actually happened.*

**Game log:**
*Upload your game log through [hastebin](https://hastebin.com/) and provide the link. Do not paste the link directly into the submission box or comments.*
The evoker does not have any skills！

**Comment by minecraftedleen** [comment]
feature request I think you should put this in discussions

**Comment by Draylar** [comment]
Evokers will have an ability in the next update: press 'R' to summon a stream of... whatever the chompy things are!
