### ISSUE TITLE
Iron golem and ravager twitch when they attack

### ISSUE THREAD

**Issue by kridb** [Draylar/identity#254]
**Bug description**
*A description of what you expected to happen and what actually happened.*

**Game log:**
*Upload your game log through [hastebin](https://hastebin.com/) and provide the link. Do not paste the link directly into the submission box or comments.*

**Comment by minecraftedleen** [comment]
can confirm

**Comment by Draylar** [comment]
Fixed in the next update, thanks for the report :)
