### ISSUE TITLE
Blazes cannot be shot with arrows

### ISSUE THREAD

**Issue by FinalBosses** [Draylar/identity#27]
I am hosting a server with multiple mods, including the identity mod. Whenever someone is a blaze and gets shot by an arrow, the server crashes. The crash report says that it is a ticking entity. The entity is an arrow. To fix this, I tell the blazes not to join. Then I go into creative and place down a repeating command block with the code: `kill @e[type=minecraft:arrow]`
I tell the blazes to get on. After they have been in the game for a around 10 seconds, I destroy the command block and go back to playing in survival.

To fix this, I have placed a chain of command blocks with this code:
First command block, repeating, unconditional and always active: `execute as @e[type=!#identity:hurt_by_high_temperatures] at @s run execute as @e[type=minecraft:arrow,distance=..3] run effect give @p[distance=..3] minecraft:resistance 1 2 true`
Second command block, chain, unconditional and always active: `execute as @e[type=!#identity:hurt_by_high_temperatures] at @s run execute as @e[type=minecraft:arrow,distance=..3] run effect give @p[distance=..3] minecraft:instant_damage 1 1 true`
Third command block, chain, conditional and always active: `execute as @e[type=!#identity:hurt_by_high_temperatures] at @s run execute as @e[type=minecraft:arrow,distance=..3] run kill @e[type=minecraft:arrow,distance=..3]`

Is anyone else having this issue?

**Comment by James103** [comment]
Do you have the exact crash report (which contains the stack trace and which mods and versions are being used)?

**Comment by FinalBosses** [comment]
yes, here it is:
[crash-2020-07-29_18.13.42-server.txt](https://github.com/Draylar/identity/files/5002434/crash-2020-07-29_18.13.42-server.txt)

**Comment by FinalBosses** [comment]
Also, I forgot to mention, The command block code also effects bats. I have not tested it with other morphs, but I don't think bats fall into the category of `!#identity:hurt_by_high_temperatures`

**Comment by FinalBosses** [comment]
I just tried to start up my server, and it crashed. This wasn't a normal crash. It crashed before even getting half way through starting up. No chunks were loaded, and it was around 20 seconds before the server would be open. I don't know how I can fix this. I can't go onto the server and place down a command block. I can't even run a command before the server crashes. I can't do anything.

**Comment by James103** [comment]
1. If different from your other crash report, do you have the crash report from the crash-on-startup?
2. Have you tried starting up an (otherwise) identical server but with a fresh new world?

**Comment by FinalBosses** [comment]
1. No, it didn't even leave a crash report. The terminal just closed
2. No, I will try that.

**Comment by FinalBosses** [comment]
I just tried it with a fresh new world, and it got farther in starting up, but still crashed around a second before it would start generating a spawn point.

**Comment by James103** [comment]
Same crash (no crash report) or did it actually generate a crash report?

**Comment by FinalBosses** [comment]
No crash report

**Comment by FinalBosses** [comment]
Would you like my server folder, so you could try it yourself?

**Comment by FinalBosses** [comment]
I just checked, and it turns out that the server is up while the terminal is closed. I don't know what is going on, but the worlds just swapped while the server was up when I switched the world files. This is really weird.

**Comment by FinalBosses** [comment]
the folder is compressing

**Comment by FinalBosses** [comment]
Here it is: https://drive.google.com/file/d/1l4L_0Md7W490PQeDPJuQ8ZZPYCFmg_KX/view?usp=sharing

**Comment by Draylar** [comment]
I'll look into this when I get home 👍

**Comment by Draylar** [comment]
According to the log you posted, this is an issue with [Mo' Enchantments](https://gitlab.com/biom4st3r/moenchantments), not Identity. The log reveals [this method](https://gitlab.com/biom4st3r/moenchantments/-/blob/default/src/main/java/com/biom4st3r/moenchantments/EventHandlers.java#L110) is culprit, which is (interestingly enough) commented out and renamed compared to the latest jar on CurseForge. Seems like they assume _every_ damage causing entity is a `LivingEntity` (and arrows are not). The game should crash every time you shoot _anyone_ with an arrow-- not just Blazes. Is this the case?

My guess is they removed the method because it was crashing in dev, but never pushed a fix version. If there is a separate crash not related to arrows, I would need a crash log. If the command prompt closes before you can copy it, [follow these instructions](https://stackoverflow.com/questions/17118846/how-to-prevent-batch-window-from-closing-when-error-occurs).

I'll keep this open until you solve the issue, but I don't think it (at least, the arrow part) is Identity's fault.

**Comment by FinalBosses** [comment]
Thank you, I will wright an issue for Mo' Enchantments. Also, the `!#identity:hurt_by_high_temperatures` including bats, is that also Mo' Enchantments's fault?

**Comment by Draylar** [comment]
My `hurt_by_high_temperature` tag _only_ includes Snow Golems. Not sure why it's returning true for bats.

![image](https://user-images.githubusercontent.com/17728338/88977699-ff0fdd80-d283-11ea-9b61-04099bf23d73.png)

**Comment by James103** [comment]
@FinalBosses Do you have any datapacks enabled? If so, could you try disabling them? At least one datapack may be overriding the `#identity:hurt_by_high_temperature` tag and making it include bats.

**Comment by FinalBosses** [comment]
I don't have any data packs. Also, the `!#identity:hurt_by_high_temperatures` includes bats, not `#identity:hurt_by_high_temperatures`. I thought it meant that it was fire resistant if it was `!#identity:hurt_by_high_temperatures`, but now I understand what it means.

**Comment by FinalBosses** [comment]
I am not sure if this is a problem with the Identity mod, but creepers crash my game every 1 to 15 minutes. Here is the crash report:
[crash-2020-07-27_12.26.25-server.txt](https://github.com/Draylar/identity/files/5004539/crash-2020-07-27_12.26.25-server.txt)
I placed a repeating command block to kill all creepers, so this is the last crash report I have from before then. If it isn't Identity, could you tell me what it is?

Thanks,
RM

**Comment by Draylar** [comment]
You're using Identity 1.3.0, while the latest version is [1.5.0](https://github.com/Draylar/identity/releases/tag/1.5.0-beta-1.16.1). The Creeper issue was fixed in one of the newer versions.

edit: and `!` before tags means "_not_ this," so it's going to include anything besides Snow Golems.

**Comment by FinalBosses** [comment]
I just downloaded the latest version of Identity! I know what the `!` means, I just figured that "not hurt by high temperatures" would mean "fire resistant". 

Thanks for all your help,
RM
