### ISSUE TITLE
Attacked while morphed

### ISSUE THREAD

**Issue by Nickstertjefloor** [Draylar/identity#273]
I don't know if this really is an issue or it was a bug in an earlier version.

I morphed into a Zombie so I wouldn't get attacked while looting a dungeon, but I got killed by a zombie, thinking it was because I hit it, but then I respawned (as zombie still) and I got shot by a skeleton.

In 1.6.5 I wouldn't get attacked or anything while morphed, except as animal or player. I hope that what I have now is a bug, and not what it was meant to be, cause I really like that feature and it makes tje most sense.

**Comment by James103** [comment]
Try reproducing with the following setup:
1. Use Minecraft 1.17.1.
2. Use Identity 1.15.0.
3. In the identity config, set `hostilesIgnoreHostileIdentityPlayer = false`.
4. In the identity config, set `hostilesForgetNewHostileIdentityPlayer = false`.

**Comment by Nickstertjefloor** [comment]
@James103 I looked, but Identity doesn't have a config. button. There Is also no command to type☹️. I have 1.15.0-1.17.1

**Comment by realflow100** [comment]
@Nickstertjefloor You will want to go into the .minecraft folder to find the config folder. with all the mods config files directly accessible.
Then find the one for identity mod. open it up in a text editor and edit the line directly. then save it. and make sure you save it as the right file format.
I don't believe its accessible in-game. Theres no in-game config button yet.
