### ISSUE TITLE
Crash when in the presence of a ravager

### ISSUE THREAD

**Issue by chronosacaria** [Draylar/identity#276]
**Bug description**
I was in the presence of a ravager and I was blocking its attacks. The blocking didn't appear to cause any issues, but after blocking several times and it being stunned, I backed up and dropped my shield and the game crashed. When I checked the code that was referenced, I did see mention of ravagers, so I am assuming that it had something to do with the ravager rather than the blocking. This was on 1.16.5 using Java 16. If you're not taking bug reports for 1.16.5 anymore, I understand :)

**Game log:**
[Crashlog](https://hastebin.com/ixakumoved.yaml)

**Comment by James103** [comment]
The log file is expired. Can you please try reproducing it with Identity 1.15.0 and Minecraft 1.17.1? If you can reproduce the bug, upload the log file to paste.ee or pastebin.

Note: Even though Hastebin states that "Pastes will stay for 30 days from their last view.  They may be removed earlier
and without notice.", pastes on Hastebin actually expire after only a few days (maybe 7-30 days _at most_).

**Comment by chronosacaria** [comment]
Ah, sure thing. I didn’t realise that. I'll try to reproduce it tomorrow

**Comment by chronosacaria** [comment]
Sorry for taking so long to test this. It appears that this issue is resolved in the latest version. Thanks for letting me know to test the latest build, @James103
