### ISSUE TITLE
Can't fly

### ISSUE THREAD

**Issue by FinalBosses** [Draylar/identity#28]
At first, the mod was working fine. Then I got the bat identity, and I started to notice that every time I re-spawned I couldn't fly. All I had to do was click on the bat identity again, and I would be able to fly. I recently switched to version 1.5.0 of the Identity Mod (I was previously playing on version 1.3.0), and now it's gotten worse. When I re-spawn, I can't fly until I completely disconnect and reconnect to the game. If I turn into a blaze, I still don't fly. If I turn back into a bat, I still don't fly. I can only fly if I disconnect and reconnect. I hope there is a fix.

Thanks,
RM

**Comment by James103** [comment]
If the mod is configured to require advancements for flight, have you tried giving yourself all advancements? If the mod is configured to disable flight altogether, have you tried re-enabling flight on the server side?

**Comment by Draylar** [comment]
I've confirmed the issue, talking to Pyro about how to fix it

**Comment by Draylar** [comment]
Fixed in 1.5.1 beta, thanks!
