### ISSUE TITLE
Identity Mod Corrupting Player Data

### ISSUE THREAD

**Issue by Jimbits-zz** [Draylar/identity#282]
Hi there,

My son uses this mod and the game keeps crashing. After each crash the player data in Level.DAT becomes corrupted and the world can no longer be loaded. I've been using a back-up of the world to copy player data from and replace the corrupted part of Level.DAT. This allows for the world to load again and be played. But before too long, the same crash happens again and the player data is once again corrupted.

I have vanilla Minecraft, Fabric mod loader and Identity Mod installed ONLY.

Any help would be much appreciated.

**Crash Log**
https://hastebin.com/iwisebokur.properties

**Game Log**
https://hastebin.com/ekoweweman.yaml

**Comment by Draylar** [comment]
Sorry, accidentally turned web notifications off so I missed your issue. Did you manage to solve the problem? If not, would you mind uploading to pastebin instead (the hastebin links appear to be empty)?

**Comment by Jimbits-zz** [comment]
Hi there, that's no problem thank you for getting back to me :) I haven't found a permanent solution, I am still using NBTExplorer just to copy player data from a backup to the current world whenever this happens. I'm not sure what is triggering the crash but whenever my son is playing it will happen at least a few times. 

I'm not sure why the hastebin links aren't working, they seem to be for me but I'm kinda new to hastebin so maybe it's something I've done wrong. Here are some pastebin links that will hopefully work:

**Crash Log**
https://pastebin.com/z4DHL90v

**Game Log**
https://pastebin.com/Azg78CWQ

Thanks again for getting back to me, and thank you/well done for making such a great mod, my son loves to play as the other creatures (especially the wolves) so your mod is perfect for him :D

**Comment by Draylar** [comment]
You are using Identity 1.14.0-beta-1.17, which unintentionally bundled a library that fixes an old 1.16 bug (& it crashes on 1.17.1). If you update to the latest [1.14.2 version](https://www.curseforge.com/minecraft/mc-mods/identity/files/3363974) your issue should be fixed. Please let me know if you encounter any other problems!

**Comment by Jimbits-zz** [comment]
Ah ok, I didn't realise I was out of date. Could have sworn I'd downloaded the latest version but obviously not. I'll install the correct version now and see how we go. Thank you again for getting back to me and helping us out :D

**Comment by Jimbits-zz** [comment]
Just as a quick follow-up, no further issues after updating. Thanks again @Draylar for your help.
