### ISSUE TITLE
Identity GUI Not appearing

### ISSUE THREAD

**Issue by lordofpotatos** [Draylar/identity#286]
I'm running Identity as a server-side mod but when I use the key that it says on curseforge it doesn't work and when I kill a mob to unlock the identity it doesn't say identity unlocked it says identity.unlock something I forgot so does anyone have any fixes?

Version: identity-1.14.2-beta-1.17

**Comment by James103** [comment]
> I'm running Identity as a server-side mod

Identity must **also** be installed on the client-side in order to work properly.
