### ISSUE TITLE
Bug with kibe

### ISSUE THREAD

**Issue by kadir1243** [Draylar/identity#289]
**Bug description**
*Using kibe Diamond Spike*

**Game log:**
*[log](https://hastebin.com/yitalobuca.yaml).*

*Mod Version:1.14.2-beta-1.17*
*Minecraft Version:1.17.1*
*Kibe Version:1.8.1-BETA+1.17*

**Comment by Draylar** [comment]
Having trouble reproducing & can't see your log, feel free to post another log if you are still encountering the problem after the next update

![image](https://user-images.githubusercontent.com/17728338/136140680-c86dda54-3813-48d2-b4a4-b1a4e642cc5a.png)
