### ISSUE TITLE
Identity config (suggestion)

### ISSUE THREAD

**Issue by AndronixESE** [Draylar/identity#292]
Hi, im wrighting you becouse i would like to suggest a really cool feature to the identity mod. I would be really happy if you could make it come true. Could you make that in config people would be able to edit how many times do you have to kill a certain mob to get its morph? It would make this mod little bit less OP and more customizable. Please concider making it, with my best wishes, Andronix

**Comment by Draylar** [comment]
Thanks for the suggestion, this will be out in 1.15.0 beta (released in a bit)! I also added a [wiki](https://github.com/Draylar/identity/wiki/Kill-Requirements) page with information on the configuration options. Let me know if it works out!
