### ISSUE TITLE
can't edit witch ability coldown

### ISSUE THREAD

**Issue by minetyp2232** [Draylar/identity#293]
i am trying to edit the "identity.5json" in configs file but i relised that there is no settings to edit the witch ability coldown , the witch throwing the potions bottles but the coldown so slow so i tried to make it faster but i didnt find how ? i can edit other mobs abilitys coldown like wither, creeper, blaze... but can't find any text that tell me if i can edit the witch ???
if you fix this please make it work in 1.16.5 too ,thank you .

**Comment by Draylar** [comment]
Done - https://github.com/Draylar/identity/releases/tag/1.13.3-1.16.5 provides a new map at the bottom where you can configure specific entity cooldown values. Example:
```json
"abilityCooldownMap": {
    "minecraft:blaze": 20,
    "minecraft:enderman": 10,
    "minecraft:creeper": 100,
    "minecraft:wither": 200,
    "minecraft:ghast": 60,
    "minecraft:ender_dragon": 20,
    "minecraft:snow_golem": 10,
    "minecraft:witch": 200
  }
```
The value is in ticks. I also decreased the default cooldown from 15 seconds to 10 seconds. Enjoy!
