### ISSUE TITLE
Most recent release is "1.133" instead of "1.13.3"

### ISSUE THREAD

**Issue by James103** [Draylar/identity#294]
**Bug description**
Your most recent GitHub Release of the mod at https://github.com/Draylar/identity/releases/tag/1.13.3-1.16.5 is:
"1.133 - cooldown configuration for 1.16.5"

The correct title of the release is:
"1.13.3 - cooldown configuration for 1.16.5"

**Game log:**
Bug in metadata; game log not applicable here.

**Comment by Draylar** [comment]
Oops, thanks for letting me know😂
