### ISSUE TITLE
Multiplayer players can’t see friends’ deformed creatures

### ISSUE THREAD

**Issue by Nxs233** [Draylar/identity#307]
In multiplayer mode, you can’t see your friend’s transformation effect, but you can see your own effect (1.17.1 forge)

**Comment by Draylar** [comment]
Thank you for the report - I've jumped around on 2 accounts for a while after implementing a fix for this, and it seems to be solved. If you end up trying out the new 2.1.0 alpha update for 1.17 Forge, let me know how it works out!
