### ISSUE TITLE
1.16.1 Identity and optifine caused the game to crash

### ISSUE THREAD

**Issue by Meteor-Rainning** [Draylar/identity#31]
The mod cannot run with Optifine. Also, my identity is not shown in the game.
<img width="966" alt="截屏2020-08-12 下午9 47 17" src="https://user-images.githubusercontent.com/69588575/90022679-66e31100-dce5-11ea-8033-ab5f19998666.png">

[crash-2020-08-12_21.36.41-client.txt](https://github.com/Draylar/identity/files/5063063/crash-2020-08-12_21.36.41-client.txt)

**Comment by Draylar** [comment]
I don't support OptiFine (the crash is their fault, nothing I can do). I'm not sure about the rendering issue-- I fixed something similar in 1.5.1, but you're already on it. My only guess is Immersive Portals, but I will look into it more when I update the mod to 1.16.2
