### ISSUE TITLE
Identities disappear when i die

### ISSUE THREAD

**Issue by Bovack** [Draylar/identity#312]
whenever I die, the identities I gathered resets, I'm not sure if this is apart of the mod or not but I'm wondering if there is any fix to this so my morphs in my morph menu doesn't reset every death

**Comment by oliver408i** [comment]
Try killing a mob

**Comment by Draylar** [comment]
This should be fixed in the next 2.1.0 alpha update for 1.17 Forge, although I've only tested a few obvious cases of this occurring - please let me know if you re-encounter the problem again. Have fun, and thanks for the report!
