### ISSUE TITLE
Morphing stops after entering another dimension.

### ISSUE THREAD

**Issue by strudelagain** [Draylar/identity#313]
After going through any portal, in my case the nether portal and twilight forest portal, all my morphs disappeared and killing the mob again didn't bring it back. This also includes going from the nether/twilight forest to the overworld, whether by portal or by dying.

**Comment by Draylar** [comment]
[Fixed (probably:tm:)](https://streamable.com/fb77s3) in the next 2.1.0 alpha update for 1.17 Forge. If you get a chance to try it out, let me know if it works! Thanks for the report!
