### ISSUE TITLE
Improper animation for projectiles.

### ISSUE THREAD

**Issue by UmbreoClaw** [Draylar/identity#32]
If you are any type of entity (skeleton, piglin, drowned, pillager, etc) the animations for arming the projectile is absent. or when you shoot arrows as a skeleton, it doesn't show the animation for the arming of the bow. when a pillager or piglin arms their bow they usually "touch" the crossbow to arm it. but in the transformation there is no animation. Also when a piglin has a loaded crossbow it should be held up, but it isnt. when a drowned is throwing a trident it usually holds up its arm, but when you are transformed, the animation for throwing it is absent.

Thank you for taking your time to read my comment. 👍

**Comment by James103** [comment]
Related to (possible duplicate of) #12

**Comment by UmbreoClaw** [comment]
@James103 I guess :/

**Comment by Draylar** [comment]
I spent a while trying to figure this out. It's cursed and I didn't make much progress. I will look at it again soon. Thanks for the report!

**Comment by jviteo2005** [comment]
haha sorry for my broken english

**Comment by jviteo2005** [comment]
@Draylar are you going to make custom hand overlays of the mobs. like if you have a zombie identity on, your hand will look like a zombie hand

**Comment by Draylar** [comment]
![image](https://user-images.githubusercontent.com/17728338/99202790-efa29a80-2775-11eb-8743-a02edaa99f3e.png)

🥳🎊🎈🎉 this took way too much time, but it works 🥳
