### ISSUE TITLE
Crashing when hitting Straddler from Alex's Mobs

### ISSUE THREAD

**Issue by SirKrunk** [Draylar/identity#321]
**Crashing when hitting Straddler from Alex's Mobs**
*ModLoader: Forge
  Identity Version: identity-forge-2.0.0-1.17.1-beta.jar
  Architectury API version: [Forge 1.17.1] v2.9.3
  Using any morph, I crit Straddlers(Alex's Mobs) and the game immediately crashes. Looking through the crash report, it says something about hostility*

**Game log:**
*https://pastebin.com/88NGF1jD*

**Comment by James103** [comment]
Same error as #308 and #311

**Comment by SirKrunk** [comment]
any chance draylars gonna fix this?

**Comment by Draylar** [comment]
Working on it now 💪

**Comment by Draylar** [comment]
Okay, this should be fixed in the next 2.1.0 alpha update for Forge on 1.17 (released in a few hours on CF) - let me know if it works out for you. Once I get a seal of approval from a few players, I will push the update out to 1.18 Forge as well. Thank you for the report!

**Comment by SirKrunk** [comment]
yay!
