### ISSUE TITLE
Any ETA of the 1.18 update yet?

### ISSUE THREAD

**Issue by Spiderfffun** [Draylar/identity#322]
Really looking forward to using it

**Comment by oliver408i** [comment]
there is banch for 1.18. Check the pull requests

**Comment by beautiful-lunatic** [comment]
> there is banch for 1.18. Check the pull requests

What exactly are pull requests? Does that mean its being updated or does that mean people are requesting for it to be updated? (Im dumb about things like this, sorry!)

**Comment by oliver408i** [comment]
basically a pull request is when someone wants the owner to do something to the main repo. It means people are requesting for it to update.

**Comment by Draylar** [comment]
Hey all, sorry for the delay on the update - I was aiming to get the Forge + Fabric versions running on the same branch for 1.18.1 using Architectury (to avoid wiping Identity data in an update mid-major-version), but I ended up having less time than anticipated to get this done. That being said, I'll merge the PR for 1.18.1 tonight, push out a release, and wait to update Forge until a later version. 

If I forget to send out a release tonight, feel free to spam this issue to remind me😆

**Comment by beautiful-lunatic** [comment]
> Hey all, sorry for the delay on the update - I was aiming to get the Forge + Fabric versions running on the same branch for 1.18.1 using Architectury (to avoid wiping Identity data in an update mid-major-version), but I ended up having less time than anticipated to get this done. That being said, I'll merge the PR for 1.18.1 tonight, push out a release, and wait to update Forge until a later version.
> 
> If I forget to send out a release tonight, feel free to spam this issue to remind me😆

Cant wait :)

**Comment by Draylar** [comment]
[1.18.1 is up thanks to Dimi](https://www.curseforge.com/minecraft/mc-mods/identity/files/3601799) - let me know how it goes! For the Forgers, look forward to a 1.18 update to Forge once the next 1.17 Forge update is sanity checked by players 😆
