### ISSUE TITLE
Wont let me join servers

### ISSUE THREAD

**Issue by Bryson-King** [Draylar/identity#324]
Every time I join a server it shows this (1.18.1) Fabric
![Screenshot 2022-01-11 162623](https://user-images.githubusercontent.com/97560270/149024096-5bbf251a-6b50-4dbc-ac87-1217725c6846.png)

**Comment by James103** [comment]
1. What mods are you running on your client?
2. What mobs is the server running?

**Comment by Bryson-King** [comment]
The server is running 0 mods and here is the list of mods i have
![Screenshot 2022-01-11 181905](https://user-images.githubusercontent.com/97560270/149036667-d801b3b9-b7e6-456d-ab41-4c475a2caace.png)

**Comment by Draylar** [comment]
You need Identity on both the client and server; this means you'll have to [install Fabric on your server](https://fabricmc.net/use/installer/) & pop the Identity .jar file into the mods folder on the server as well as your client.

If you're trying to join a non-modded server without the intention of using Identity (eg. Hypixel), I would recommend using [MultiMC](https://multimc.org/) to manage separate client-side & Identity instances.
