### ISSUE TITLE
Game crash Minecraft 1.16.1 on startup

### ISSUE THREAD

**Issue by joshuax8** [Draylar/identity#325]
**Bug description**
There seems to no working combination for 1.16.1. It looks like the mod isn't compatible with the old Fabric API 18. This is the combination used:
Minecraft 1.16.1 (default bundled Java) with Fabric loader 12.12 + identity-1.13.2-1.16.5.jar + fabric-api-0.18.0+build.387-1.16.1.jar 

I also tried the same setup but with identity-1.16.0-1.18.1.jar but that isn't compatible with the bundled Java version (`The requested compatibility level JAVA_16 could not be set. Level is not supported by the active JRE or ASM version (Java 1.8, ASM 9.2 (ASM10_EXPERIMENTAL))`)

The newer Fabric API versions aren't compatible with Minecraft 1.16.1.

Confirmed on both Windows 10 and Windows 11.
Would be nice to have 1.16.1 working as it's a (still) widely used version among speedrunners.

**Game log:**
https://www.toptal.com/developers/hastebin/raw/loforisisu

**Comment by Draylar** [comment]
https://www.curseforge.com/minecraft/mc-mods/identity/files/3603744 has a re-upload of 1.16.1, let me know if it works!

**Comment by joshuax8** [comment]
Works like a charm! Thanks!
