### ISSUE TITLE
glitch.

### ISSUE THREAD

**Issue by UmbreoClaw** [Draylar/identity#33]
![Screenshot (24)](https://user-images.githubusercontent.com/69083095/90323315-a0a65880-df2d-11ea-9a13-0eea67ba9952.png)
When ever I play offline the latest version and the identity mod version "link"... in the latest release box the version shows the fabric loader instead of (latest version). and i was confused on how i could fix this

**Comment by UmbreoClaw** [comment]
I have fixed it. you go into fabric loader version file and go into notepad. Change _Type: release_ to _Type: version_ and it will change the latest release back into the latest release. _Ps: sorry for my jumbled mess of words, i am coming up with the wording as i type :/_
![Screenshot (25)_LI](https://user-images.githubusercontent.com/69083095/90323424-40b0b180-df2f-11ea-9b91-ded158b02f93.jpg)

**Comment by UmbreoClaw** [comment]
This happens when you go offline

**Comment by UmbreoClaw** [comment]
it will say _Type: release_ until you change it to _Type: version_

**Comment by Draylar** [comment]
This isn't related to Identity. If you need to open an issue with Fabric Loader, head over to their GitHub page [here](https://github.com/FabricMC/fabric-loader). If you need support with Fabric, join the Discord server [here](https://discord.gg/v6v4pMv) and go to #player-support. I don't use the vanilla launcher (I use MultiMC), so I'm not sure how to fix your issue.
