### ISSUE TITLE
Can't reach max Hoglin health

### ISSUE THREAD

**Issue by Egon370** [Draylar/identity#337]
I'm playing as a Hoglin, but every time I respawn I have 15 hearts instead of 20. I don't see an option to change this in the config either.

**Comment by Draylar** [comment]
![image](https://user-images.githubusercontent.com/17728338/170608429-5c068ccc-d84d-46f9-bcbf-83a9383eddfe.png)

There's a chance this was related to the health issue I recently fixed - I can now see 20 full hearts in my play environment. Let me know if you run into the issue again in the future. Have fun! :)
