### ISSUE TITLE
When I right-click to a ravager, the game crash

### ISSUE THREAD

**Issue by Wonktodi** [Draylar/identity#339]
**Bug description**
*Just as the title. however when i equip an Identity, this won't happen.
1.18.1fabric , only use Identity mod.*

**Game log:**
**latest.txt** [https://www.toptal.com/developers/hastebin/arupesoxej.yaml](url)
**crash-2022-02-20_13.33.21-client.txt**  [https://www.toptal.com/developers/hastebin/copajesufi.yaml](url)

**Comment by James103** [comment]
Converted the pastes to text files as the pastes expire in less than 7 days.
[latest.log](https://github.com/Draylar/identity/files/8103583/latest.log)
[crash-2022-02-20_13.33.21-client.txt](https://github.com/Draylar/identity/files/8103584/crash-2022-02-20_13.33.21-client.txt)

**Comment by Draylar** [comment]
Fixed, thanks!
