### ISSUE TITLE
Boat riding animation

### ISSUE THREAD

**Issue by UmbreoClaw** [Draylar/identity#34]
When riding a boat as another mob (ex. Piglin, zombie, skeleton). the mob does not "sit". The mobs legs go through the boat whereas they should be sitting. this affects all mobs. Sorry for so much feedback
![Identity mod 1 16 1 Piglin in boat glitch](https://user-images.githubusercontent.com/69083095/90346339-065e1780-dff6-11ea-93a2-6ce21d567648.png)

**Comment by UmbreoClaw** [comment]
this is the latest version of the identity mod

**Comment by Draylar** [comment]
Fixed in 1.6.0 for 1.16.1, thanks for the report~

![image](https://user-images.githubusercontent.com/17728338/93655270-016ef800-f9e8-11ea-8181-59e384ecd523.png)
