### ISSUE TITLE
1.18.2 version is missing

### ISSUE THREAD

**Issue by CreeperPeruano** [Draylar/identity#347]
**Description**
*So i remember there was a 1.18.2 version before, but I think after the license change it went missing. If it was never there, I would like a 1.18.2 version, as this mod is the best!*

**Comment by Shadowysn** [comment]
Was there really a momentary 1.18.2 version? It sounds like it might've been an unstable version that had to be pulled out.
Do you have any proof?

**Comment by beautiful-lunatic** [comment]
I wish there was a 1.18.2 version!

**Comment by Draylar** [comment]
Thanks to the help of the lovely CDAGaming, 1.18.2 releases are now here for Fabric & Forge! Have fun and let me know if you run into any issues.
