### ISSUE TITLE
Crashing and saying -invalid player data- when trying to join my single player world

### ISSUE THREAD

**Issue by beautiful-lunatic** [Draylar/identity#352]
---- Minecraft Crash Report ----
// Don't do that.

Time: 2022-05-26, 10:54 a.m.
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8510()" because the return value of "qouteall.imm_ptl.core.McHelper.getOverWorldOnServer()" is null
	at qouteall.imm_ptl.core.McHelper.getServerGameTime(McHelper.java:104)
	at qouteall.imm_ptl.core.teleportation.ServerTeleportationManager.tick(ServerTeleportationManager.java:374)
	at qouteall.q_misc_util.my_util.Signal.lambda$connectWithWeakRef$1(Signal.java:35)
	at qouteall.q_misc_util.my_util.Signal.lambda$emit$0(Signal.java:18)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at qouteall.q_misc_util.my_util.Signal.emit(Signal.java:18)
	at net.minecraft.server.MinecraftServer.handler$bpl000$onServerTick(MinecraftServer.java:4327)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:930)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 765429176 bytes (729 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.42
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1218
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18483.28
	Virtual memory used (MB): 10317.26
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 146.50
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionaladditions: Additional Additions 4.0.2
		additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
		additionalstructures: Additional Structures 3.0.3
		adorn: Adorn 3.4.0+1.18.2
		apoli: Apoli 2.3.3
		architectury: Architectury 4.1.36
		artifacts: Artifacts 7.0.3+fabric
		awesomedungeonend: Awesome Dungeon Edition end 1.0.1
		awesomedungeonnether: Awesome Dungeon Edition Nether 1.0.0
		awesomedungeonocean: Awesome Dungeon Edition Ocean 2.0.5
		balm-fabric: Balm 3.0.0+0
		biomemakeover: Biome Makeover 1.18.2-1.4.18
		blue_endless_jankson: jankson 1.2.1
		boostedbrightness: Boosted Brightness 2.1.1
		calio: Calio 1.5.1
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		caveore: Cave Spelunking 1.18.2-2.3
		charm: Charm 4.1.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_github_llamalad7_mixinextras: MixinExtras 0.0.7
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		ctov: ctov FINAL-bugfix 2
		disable_custom_worlds_advice: Disable Custom Worlds Advice 2.0
		doggomod: Doggo Mod 1.1.0
		elementalcreepers: Elemental Creepers: Refabricated 1.4.2+1.18.2
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		emeraldequipment: Emerald Equipment fabric-1.18.2-v1.0.1
		exlinecopperequipment: Copper Equipment fabric-1.18.2-v2.0.1
		exlinefurniture: Exline's Furniture fabric-1.18.2-v2.0.6
		expandability: ExpandAbility 6.0.0
		fabric: Fabric API 0.48.0+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.7+d7c144a860
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.3+801ec85b60
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.2+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.13+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.3.3+691a79b560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.10+3ac43d9560
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.2+2540745460
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.4+d1027f7d60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.3+40c91ec860
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.17+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.2+d1027f7d60
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.14+40c91ec860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.14+cca23f9360
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+40c91ec860
		fabricloader: Fabric Loader 0.14.6
		fastertools: Faster tools 1.2.0
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		fishonaleash: Fish on a Leash! 1.18.1-1.0.0
		forgeconfigapiport: Forge Config API Port 3.2.0
		friendsandfoes: Friends&Foes 1.3.4
		geodes: More Geodes 1.4.2
		grindenchantments: Grind Enchantments 1.6.3+1.18.2
		guardvillagers: Guard Villagers Fabric 1.18.2-1.0.10
		hammermod: War-Hammers Mod fabric-1.18.2-v1.0.1
		identity: Identity 2.2.0-1.18.2
		imm_ptl_core: Immersive Portals Core 1.3.9
		immersive_armors: Immersive Armors 1.3.3
		immersive_portals: Immersive Portals 1.3.9
		improvedmobs: Improved Mobs 1.18.2-1.10.7
		infinitelava: Infinite Lava 1.0-SNAPSHOT
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		libraryferret: Library Ferret 1.0.3
		lithium: Lithium 0.7.9
		mendinglevels: Mending Levels 1.0.1
		merenc: Merge Enchantments 1.2
		minecraft: Minecraft 1.18.2
		moborigins: Mob Origins 1.8.1
		modmenu: Mod Menu 3.1.0
		more_babies: More Babies 0.5.2
		mostructures: Mo' Structures 1.4.1+1.18.2
		npcvariety: NPC Variety 2.2.1
		nyfsquiver: Nyf's Quivers Fabric-0.5.0-1.18.2
		obsidianequipment: Obsidian Equipment fabric-1.18.2-v1.0.1
		omega-config: OmegaConfig 1.2.3-1.18.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		org_joml_joml: joml 1.10.2
		origins: Origins 1.4.1
		playerabilitylib: Pal 1.5.0
		plushies: Plushie Mod 1.2
		q_misc_util: QMiscUtil 1.3.9
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 4.1.7+1.18.2
		roughlyenoughitems: Roughly Enough Items 8.1.457
		skinlayers: 3d Skin Layers 1.4.4-mc1.18.2
		sodium: Sodium 0.4.1+build.15
		spawnermod: Enhanced Mob Spawners 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		t_and_t: Towns and Towers - Structure Add-on 1.6
		tenshilib: TenshiLib 1.18.2-1.6.7
		torohealth: ToroHealth Damage Indicators 1.18-fabric-2
		trinkets: Trinkets 3.3.0
		walljump: Wall-Jump! 1.4.1+1.18.2
		waystones: Waystones 10.0.0
		xaeroworldmap: Xaero's World Map 1.20.7
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by Shadowysn** [comment]
Something doesn't sit right with Identity 1.18.2 and specific mods, like [Comforts (Fabric)](https://www.curseforge.com/minecraft/mc-mods/comforts-fabric/)
And when **Invalid Player Data** happened for me, I had tried to load into a 1.18.1 world.
It didn't crash, but when I tried to create a new world, it crashed at 49% generation with the minecraft screen frozen in place, and I had to manually task-end the process.

At first I thought new items/recipes added by another mod was causing all this, but [Chest Cavity](https://www.curseforge.com/minecraft/mc-mods/chest-cavity), a mod chock-full of items and recipes, wasn't causing any problems. Though I could probably chalk **Chest Cavity** up to being better supported by more devs, but still.

I wonder when Draylar's schedule can allow them to work on this further.

EDIT: Is sharing compressed .txt files in .zips allowed? Here's the log where I had Identity and Comforts clash and cause **Invalid Player Data** for me. Didn't try to create new world though, but if Draylar suggests me to do it, I'll do it.
[log_of_comforts_incompatibility.zip](https://github.com/Draylar/identity/files/8780472/log_of_comforts_incompatibility.zip)

**Comment by beautiful-lunatic** [comment]
> Something doesn't sit right with Identity 1.18.2 and specific mods, like [Comforts (Fabric)](https://www.curseforge.com/minecraft/mc-mods/comforts-fabric/) And when **Invalid Player Data** happened for me, I had tried to load into a 1.18.1 world. It didn't crash, but when I tried to create a new world, it crashed at 49% generation with the minecraft screen frozen in place, and I had to manually task-end the process.
> 
> At first I thought new items/recipes added by another mod was causing all this, but [Chest Cavity](https://www.curseforge.com/minecraft/mc-mods/chest-cavity), a mod chock-full of items and recipes, wasn't causing any problems. Though I could probably chalk **Chest Cavity** up to being better supported by more devs, but still.
> 
> I wonder when Draylar's schedule can allow them to work on this further.
> 
> EDIT: Is sharing compressed .txt files in .zips allowed? Here's the log where I had Identity and Comforts clash and cause **Invalid Player Data** for me. Didn't try to create new world though, but if Draylar suggests me to do it, I'll do it. [log_of_comforts_incompatibility.zip](https://github.com/Draylar/identity/files/8780472/log_of_comforts_incompatibility.zip)

I don't have comforts btw.


Also, taking everything out and leaving fabric api and identity causes the game to just not open and immediately crashing.

**Comment by Draylar** [comment]
Oops, accidentally left a Cardinal Components entry in the fabric.mod.json file, which was causing a crash while CCA was installed. Comforts relies on CCA, so it would make sense that it would conflict with Identity. This issue has been fixed, but keep track of #353 for the other main problem here. Thanks for the quick report!

**Comment by Shadowysn** [comment]
> Also, taking everything out and leaving fabric api and identity causes the game to just not open and immediately crashing.

Identity 1.18.2 has started to use the [Architectury API](https://www.curseforge.com/minecraft/mc-mods/architectury-api) as a required dependency.
Without it, it will crash.
