### ISSUE TITLE
(Fabric 1.18.2 Arch) Identity list not loading properly

### ISSUE THREAD

**Issue by Shadowysn** [Draylar/identity#353]
**Bug description**
When loading a saved world, the identity list is not being loaded properly.
The list is blank and nothing is selectable, but the commands like **/identity grant** still think the previous saved identities are still there.

Loading my 1.18.1 world also reverted my current identity back to a player, but still keeping the lesser max health of the identity.
There also seems to be a change in where the NBT data for identity is stored. **Is 1.18.1 data intended to be moved/altered to work for 1.18.2?**

Here's the lines where the identity list troubles start:
[Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "draylar.identity.impl.PlayerDataProvider.getFavorites()" because "data" is null

In the log, I first load up my 1.18.1 world _(also destroying other things from other mods, i made a backup so no issue there)_, then go on to make a temporary world called 'f*ck' to test the identity list.
Using the latest versions of Architectury, Fabric API, and Identity 1.18.2.

**Game log:**
https://www.toptal.com/developers/hastebin/xigibufili.sql

**Comment by Draylar** [comment]
_Should_ be fixed now - there was a networking issue when sending data to players on first join. Tested and working in a production 1.18.2 Fabric instance.

To clarify, 1.18.1 Identity data will not / should not transfer to 1.18.2. It is a breaking update. The new Fabric version uses the same data-saving behavior as the Forge module, which means old data through CCA is gone. You 100% should be able to port up your 1.18.1 world and play it normally on 1.18.2, but your data on Identity unlocks will be wiped. 

Let me know if you run into any issues with the new version - thanks for the report!

**Comment by Shadowysn** [comment]
The issue seems to be fixed now. 👍

I'll use an NBT data editor to move 1.18.1 data to 1.18.2. Not the cleanest or safest solution, but it works.
