### ISSUE TITLE
(Fabric 1.18.2+1.19 Arch) Fox morphs not showing up on list

### ISSUE THREAD

**Issue by Shadowysn** [Draylar/identity#355]
**Bug description**
Both types of fox morphs don't show up on the list in _identity-2.3.0_ and later versions, both in granted/survival and creative.
You're unable to morph into a fox without **/identity equip** which works as normal.

**Screenshot:**
![no_fox](https://user-images.githubusercontent.com/44493487/170825676-00133d70-c134-4317-9ac5-4e1de17af2f9.png)

**Comment by PsychoBreadstick** [comment]
Yeah, I've also noticed this while playing around with the new version.

**Comment by MunnzKinz** [comment]
Here's a solution I found! Type in "/identity equip (username) Minecraft:fox"
It won't appear in the morph menu but it will morph you into the fox. Any time that you want to shift into a fox just type the command in!
