### ISSUE TITLE
Bees can't fly, no instructions how to use abilities (explode as creeper)

### ISSUE THREAD

**Issue by aaawertghgefwdq** [Draylar/identity#36]
Bees aren't able to fly in version 1.16.1 if you are one, and I cant figure out how to use mob abilities.

**Comment by James103** [comment]
Mob abilities cost various items to use. For example, a Creeper's explosion costs gunpowder, while a fireball thrown out of a Blaze or Ghast costs Blaze Powder and Fire Charges respectively. To teleport as an Enderman costs ender pearls. To use the ability, hold the required item and press the use key.

**Comment by aaawertghgefwdq** [comment]
> Mob abilities cost various items to use. For example, a Creeper's explosion costs gunpowder, while a fireball thrown out of a Blaze or Ghast costs Blaze Powder and Fire Charges respectively. To teleport as an Enderman costs ender pearls. To use the ability, hold the required item and press the use key.

Okay!! Thank you so much :D!

**Comment by Draylar** [comment]
Just made [this page](https://github.com/Draylar/identity/wiki/Abilities), which should help out a little bit with the current Abilities. Thanks for the help, James! Going to leave this open so I remember to add Bees to the flight tag.

**Comment by aaawertghgefwdq** [comment]
> Just made [this page](https://github.com/Draylar/identity/wiki/Abilities), which should help out a little bit with the current Abilities. Thanks for the help, James! Going to leave this open so I remember to add Bees to the flight tag.

Thank you so much! although there might be minor issues, I really love your mod! I've been trying to find a morph mod since iChun's, and this one is really nice so far 👍

**Comment by Draylar** [comment]
Bees will be able to fly in the 1.6.0 version (for 1.16.1) when it is released. Thanks for the report!
