### ISSUE TITLE
Cannot use Warden's ability (Forge 1.19)

### ISSUE THREAD

**Issue by MasterOpel** [Draylar/identity#366]
When I am using the Warden identity, and I press my key for using the ability, the Sonic Boom does not come out. I have attached some screenshots as proof:
![2022-06-30_09 27 27](https://user-images.githubusercontent.com/104687131/176703526-6bae7baa-a35c-44c5-8815-5def6b36e5c6.png)
![2022-06-30_09 33 24](https://user-images.githubusercontent.com/104687131/176704225-8fcfa368-5cf2-47a1-9e55-551483d79e29.png)
![2022-06-30_09 27 43](https://user-images.githubusercontent.com/104687131/176703534-9846eaff-4da1-4cc4-9ada-4cd7f8cb18f6.png)

Installed mods:
- Architectury 5.7.28
- Identity 2.40

**Comment by Enderstyle** [comment]
There is no ability

**Comment by MasterOpel** [comment]
> There is no ability

No, the Warden's ability is the Sonic Boom.

**Comment by Enderstyle** [comment]
For the actual mob yes but you cant use the ability when you are disguised as the warden. I hope they add this soon.

**Comment by MasterOpel** [comment]
> For the actual mob yes but you cant use the ability when you are disguised as the warden. I hope they add this soon.

Yeah, that is true.

**Comment by Draylar** [comment]
![image](https://user-images.githubusercontent.com/17728338/179134604-c2cc3320-96c0-4a63-8218-581f6b0f155b.png)

Warden ability support is out in the next update. Have fun!
