### ISSUE TITLE
Warden identity does not give Blindness effect

### ISSUE THREAD

**Issue by James103** [Draylar/identity#368]
As shown in screenshots in #366, the latest version of Identity mod (2.4.0) does not apply the Blindness effect to players whose current Identity is a Warden.

Wardens are supposed to be blind creatures; therefore, anyone disguised as one should get the Blindness effect.

<details>

<summary> (This can already be implemented in a data pack; click this text to see an example) </summary>

`load.mcfunction`
```mcfunction
scoreboard objectives add disguised_as_warden dummy
```

`tick.mcfunction`
```mcfunction
execute as @a store result score @s disguised_as_warden run identity test @s warden
effect give @a[scores={disguised_as_warden=1}] blindness 1
```

</details>

**Comment by Enderstyle** [comment]
I don't think that is a good idea because it will ruin the player's experience.

**Comment by James103** [comment]
If not Blindness, how about the Darkness effect? It still reduces effective view distance (to about 16-24 blocks max), but not as much compared to Blindness (which limits view distance to &#x2248;3-4 blocks)

**Comment by Enderstyle** [comment]
Or it gives the entities around them the darkness effect to make it so its like an actual warden.

**Comment by jzrlza** [comment]
Make this configurable in the ".minecraft/config/indentity.json5" file, I think in my opinion, it is a great idea for a more challenging experience to have a blindness effect as a Warden anyway, since this mob is already overpowered (also needs a laser ability), think about Wildmutt in Ben10 (yes, my childhood show, not a big fan of it now).

**Comment by Enderstyle** [comment]
Yeah I think this is a good idea.

**Comment by Draylar** [comment]
Done & done - you can check the `wardenIsBlinded` and `wardenBlindsNearby` to toggle darkness for yourself or other players around you. Have fun!
