### ISSUE TITLE
Allay Flight

### ISSUE THREAD

**Issue by Enderstyle** [Draylar/identity#369]
The allay does not have any flight ability.

**Comment by jzrlza** [comment]
Same goes for any other flying mobs that could fly in previous versions! (Bee,Blaze,Bat,Parrot,Vex,etc.)

**Comment by Enderstyle** [comment]
Yeah

**Comment by Natedogwoooof** [comment]
Plese

**Comment by Natedogwoooof** [comment]
> Same goes for any other flying mobs that could fly in previous versions! (Bee,Blaze,Bat,Parrot,Vex,etc.)
For me all the others work

**Comment by Natedogwoooof** [comment]
Except allay

**Comment by Draylar** [comment]
Hi Nate, the Allay can fly in 2.5.0 alongside the entities mentioned above. I think there's a small bug with the flight mechanic when you swap in and out of creative mode, which I'll also have to fix in the future (this might be related to why you can't fly with the Blaze, etc. at some points).
