### ISSUE TITLE
Frog Does 10 Points of Damage Unarmed (fabric)

### ISSUE THREAD

**Issue by AltairAlphaGames** [Draylar/identity#371]
Turn into a frog using the command /identity equip @p minecraft:frog and then punch anything.  You can confirm by summoning an iron golem and checking the health data point.  Exactly 10 points of damage with a bare fist, but normal if something is in hand.

**Comment by Natedogwoooof** [comment]
That's normal other mobs do that too but they have their own damage points like the panda Enderman Iron Golem and Warden

**Comment by AltairAlphaGames** [comment]
ROFL!!! You're telling me the MC devs gave the frogs "punch" (which is obviously not a feature) THAT level of damage?!  That's too funny!  Fair enough I guess.  Thanks for the response :)
