### ISSUE TITLE
Snowman Crash

### ISSUE THREAD

**Issue by Blue-Leaf-vm** [Draylar/identity#376]
**Bug description**
*Game crashes if you turn into a snowman.*

**Comment by James103** [comment]
Do you have the crash report? If so, can you please post it here?

**Comment by Blue-Leaf-vm** [comment]
[crash-2022-07-08_22.27.29-client.txt](https://github.com/Draylar/identity/files/9075660/crash-2022-07-08_22.27.29-client.txt)

**Comment by Draylar** [comment]
Fixed in the next update, thanks!

![image](https://user-images.githubusercontent.com/17728338/179129660-1990efff-bbc1-4435-89e0-ab4f8755890e.png)
