### ISSUE TITLE
[QoL suggestion] Favoriting Identities

### ISSUE THREAD

**Issue by praecipitator** [Draylar/identity#38]
After a while, the screen of identities gets kinda crowded. And, at least in my experience, you have only a few forms which you use regularily. 

What I propose is a way to mark identities as favorite. For example, by right-clicking them in the selection screen. This adds a star somewhere next to the identity, and favorites are always shown at the beginning of the list. That is, identities are sorted first by "favorite" status, then alphabetically.

**Comment by Draylar** [comment]
![image](https://user-images.githubusercontent.com/17728338/99197137-2a94d600-2756-11eb-84c6-d3e644784f01.png)

The menu has been updated and now supports favorites (which will always appear first). You can favorite entities by right-clicking on them. Thanks for the suggestion!
