### ISSUE TITLE
Crash when becoming a Snow Golem in Survival mode

### ISSUE THREAD

**Issue by Natedogwoooof** [Draylar/identity#380]
Drayer, So when i turned into a Snow Golem in survival mode this happened

Server: https://www.toptal.com/developers/hastebin/gaxewubexa.yaml

PS, if you can you make it so when Crouching as a snow golem you place Snow 
Client: https://www.toptal.com/developers/hastebin/eresihocem.yaml

**Comment by Draylar** [comment]
Hi Nate, can you update to Identity version 2.5.0 and let me know how it goes? I pushed it last night & it should solve your problem. Thanks for the report!

**Comment by Natedogwoooof** [comment]
> Hi Nate, can you update to Identity version 2.5.0 and let me know how it goes? I pushed it last night & it should solve your problem. Thanks for the report!

No crash happened so it's fixed and you're welcome
