### ISSUE TITLE
Foxes not on menu

### ISSUE THREAD

**Issue by Yokaiza** [Draylar/identity#387]
Foxes are not appearing in the Identity menu, both in creative mode and after I have killed one.

**Comment by James103** [comment]
What do you get in the chat / log output when you run `identity grant @s minecraft:fox`?

**Comment by Yokaiza** [comment]
I got "Yokaiza already has the Fox Identity!"
It does not appear in the identity menu, however. If i use `identity equip @s minecraft:fox` then I can morph into a fox, however it still does not show in the menu when I browse or when I search.

**Comment by James103** [comment]
Does a fox show up on the identity screen if you run `identity revoke @s minecraft:fox` followed by `identity grant @s minecraft:fox`?

**Comment by Yokaiza** [comment]
It does not-- it does not appear to be a permission issue, as the fox can still be morphed into through commands. But the fox does not appear on the menu in the fabric 1.19.1 version.

**Comment by Shadowysn** [comment]
This was an issue I've ran into back in 1.18.2 and [reported here.](https://github.com/Draylar/identity/issues/355)
Nothing has been done yet, though :V

**Comment by Draylar** [comment]
Should be fixed now, thank you!
