### ISSUE TITLE
No speed buff for Guardian, breath indicator showing

### ISSUE THREAD

**Issue by praecipitator** [Draylar/identity#39]
Just checked out the most-recent release. The swimming speed buff for fish and squid is awesome, the hidden breath indicator when under water is a nice touch.

However, these changes didn't make it to the Guardian. The reason seems to be that it doesn't extend WaterCreatureEntity, because it's hostile, therefore it extends HostileEntity instead?

**Comment by Draylar** [comment]
Fixed in 1.8.0 beta, thanks for the report :)
