### ISSUE TITLE
Fox isn't selectable in the morph Menu nor the Arctic fox

### ISSUE THREAD

**Issue by Natedogwoooof** [Draylar/identity#392]
The fox or the Arctic Fox Is not selectable in the Morph Menu but you can still morph into them by Identity/Equip Fox.
![2022-07-19_15 40 43](https://user-images.githubusercontent.com/109338104/179848174-738f1538-d82e-4184-b5bf-a4e85d72ac62.png)
![2022-07-19_15 40 57](https://user-images.githubusercontent.com/109338104/179848238-b57ecfa4-27ac-43df-8984-91019fd24890.png)

**Comment by Draylar** [comment]
Fixed, thanks!
