### ISSUE TITLE
Spinnery related crashes on 1.16.3

### ISSUE THREAD

**Issue by LlubNek** [Draylar/identity#40]
Spinnery (which is discontinued but embedded in Identity) crashes when clicking on it in the mod list (with mod menu) and when opening the player inventory.

Also, you haven't listed spinnery as a dependency on curseforge, and Fabric doesn't report what jar file it's in, which makes this sort of thing harder to track down than it should be.
I tracked it down with `grep -r spinnery *`.  Removing your mod removes Spinnery.

see https://github.com/Mixinors/Astromine/issues/311 for logs and crash reports.

**Comment by AllanChain** [comment]
Having the same problem when tring to make identity to work in 1.16.3. Don't know why spinnery is discontinued.

Mixinors/Astromine has switched to vini2003/Blade, but Blade seems not support TextField...

(Or how about switching to CottonMC/LibGui ?)

**Comment by Draylar** [comment]
Fixed in 1.9.1~
