### ISSUE TITLE
Game Crashing Trying After Clicking Singleplayer

### ISSUE THREAD

**Issue by lindseyl0u** [Draylar/identity#405]
It just saves the world and crashes. 
![9AAD8AA3-A608-4595-B8BE-9B86DFACF25D](https://user-images.githubusercontent.com/15326623/182050909-9b307e71-8196-4887-8b7a-f0f847441809.jpeg)

The game crashed whilst mouseclicked event handler
Error: java.lang.AbstractMethodError: Receiver class draylar.identity.command.IdentityCommand$$Lambda$4413/0x0000000800bf5a28 does not define or inherit an implementation of the resolved method 'abstract void register(com.mojang.brigadier.CommandDispatcher, net.minecraft.commands.CommandBuildContext, net.minecraft.commands.Commands$CommandSelection)' of interface dev.architectury.event.events.common.CommandRegistrationEvent.
Exit Code: -1

**Comment by karl134** [comment]
same

**Comment by AymKingFR** [comment]
> same

Same also
[crash-2022-08-06_19.38.10-client.txt](https://github.com/Draylar/identity/files/9275699/crash-2022-08-06_19.38.10-client.txt)

**Comment by Robnnobc** [comment]
same here

**Comment by Draylar** [comment]
Fixed in the latest release thanks to Alex & Shadow :)
