### ISSUE TITLE
Fabric 1.19.1 not working

### ISSUE THREAD

**Issue by karl134** [Draylar/identity#406]
hello I have a problem that when I try to run the game on fabric
(good files)
the game writes that I don't have this mod and I do

**Comment by karl134** [comment]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install architectury, any version.
Unmet dependency listing:
	 - Mod 'Identity' (identity) 2.4.0-1.19 requires any version of architectury, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
	at crystallauncher.MineClient.start(MineClient.java:213)
	at crystallauncher.MineClient.main(MineClient.java:36)



here error btw

**Comment by James103** [comment]
If you are running this in 1.19.1: Install the Architectury API mod, version "[Fabric 1.19.1] v6.0.35" from https://www.curseforge.com/minecraft/mc-mods/architectury-api/files, then restart the game. Does it work then?

If you are running this in 1.19, install the Architectury API mod, version "[Fabric 1.19] v5.10.33" instead (from the above link).

**Comment by Danielmarl** [comment]
Still have that problem

**Comment by Shadowysn** [comment]
Used the latest Fabric API, Architectury (v6.0.35), and Identity mod in this crash log.
Can confirm that it's definitely crashing for me in 1.19.1.
[crash-2022-08-01_15.46.21-client.zip](https://github.com/Draylar/identity/files/9231967/crash-2022-08-01_15.46.21-client.zip)

**Comment by Ausbin2** [comment]
It is crashing for me as well. I double checked that all my mods were up to date with 1.19.1 and that I was using the fabric variant of the mods instead of the forge version, as well as uninstalling and reinstalling the mods in question and Fabric itself. Nothing seems to make it stable, did the new update just break the mod?

**Comment by Ausbin2** [comment]
Im not mad or anything I just wanna know if this is an issue on my end (and if so, how to fix it) or if this is something I just need to wait for the mod creator to fix if its on their end.

**Comment by Danielmarl** [comment]
Ok Last Time When I download the 1.19 when it is in beta it is fine. Idk why it is crashing now

**Comment by Alexthw46** [comment]
Architectury changed the signature of the lamda for command registration for 1.19.1. That's the cause the error happens.
https://github.com/architectury/architectury-api/commit/b316dde8ba586cdd786555babec5c99a5ee6987a#diff-9c56954883766aecb65a871be16628ceb5758ac25c00150b1a86c99555b74c6c

**Comment by Ausbin2** [comment]
Is there a way to fix this on our end through the config file or something?

**Comment by Alexthw46** [comment]
The mod maker needs to update the mod to work with the new versions of Architectury

**Comment by Ausbin2** [comment]
Aight no sweat, I'll just chill then. Thx for the timely feedback yall 👋

**Comment by Shadowysn** [comment]
I compiled the [1.19.1 + 1.19.2 fix](https://github.com/Draylar/identity/pull/408) made by [Alexthw46](https://github.com/Alexthw46) and I hate to see others suffer without the mod, but posting the jar might risk me getting in trouble.

**Comment by InvertedCandy14** [comment]
> I compiled the [1.19.1 + 1.19.2 fix](https://github.com/Draylar/identity/pull/408) made by [Alexthw46](https://github.com/Alexthw46) and I hate to see others suffer without the mod, but posting the jar might risk me getting in trouble.

do you mean the  The game crashed whilst mouseclicked event handler
Error: java.lang.AbstractMethodError: Receiver class draylar.identity.command.IdentityCommand$$Lambda$3623/0x0000000100a05b88 does not define or inherit an implementation of the resolved method 'abstract void register(com.mojang.brigadier.CommandDispatcher, net.minecraft.class_7157, net.minecraft.class_2170$class_5364)' of interface dev.architectury.event.events.common.CommandRegistrationEvent.


issue?

**Comment by InvertedCandy14** [comment]
does it fix that?

**Comment by Shadowysn** [comment]
Yes.
Though, after a second thought I decided to [post the compiled fix in a discussion](https://github.com/Draylar/identity/discussions/422), seeing as Draylar is probably gonna be gone for a while.
I'll take it down as soon as an official 1.19.1/2 version is released.

**Comment by InvertedCandy14** [comment]
> Yes. Though, after a second thought I decided to [post the compiled fix in a discussion](https://github.com/Draylar/identity/discussions/422), seeing as Draylar is probably gonna be gone for a while.

thanks so much i recently started using the echoing depths mod and i realised it doesnt let me use identity now thanks to the jar i can use it again

**Comment by InvertedCandy14** [comment]
however does it have the wardens sonic boom thats something i really need

**Comment by InvertedCandy14** [comment]
even tho theres the echo piercing thing

**Comment by InvertedCandy14** [comment]
if not i can stick with the echo piercer

**Comment by Shadowysn** [comment]
It should have the sonic boom, the fork fix is based off the latest 1.19 version.
Just tested in game, and it does.

**Comment by InvertedCandy14** [comment]
Omg thx so much man

**Comment by Draylar** [comment]
1.19.1 on Fabric & Forge. Everyone send your thanks & appreciation to Shadowsyn & Alexthw46 for providing the patches! I'll release this version on CurseForge in a little bit after looking at fixing some other recent issues.

![image](https://user-images.githubusercontent.com/17728338/187090420-204ff3e1-867b-4114-898b-8c73fe549c94.png)

![image](https://user-images.githubusercontent.com/17728338/187090437-9a66cfdd-13c1-4324-9425-86f38de23c79.png)
