### ISSUE TITLE
Crash on creating new world in 1.19.1 with Architectury v6.1.41 for 1.19.1/2

### ISSUE THREAD

**Issue by wpatrickhames** [Draylar/identity#413]
**Bug description**
1.19.1 version fabric (identity-2.5.0-1.19-fabric.jar) crashes after load when I attempt to create a new world despite having latest architectury-6.1.41-fabric.jar file

**Game log:**
https://hastebin.com/qebifolobu.sql

**Comment by sashaironfist** [comment]
same thing:(

**Comment by InvertedCandy14** [comment]
you mean this?
 The game crashed whilst mouseclicked event handler
Error: java.lang.AbstractMethodError: Receiver class draylar.identity.command.IdentityCommand$$Lambda$3623/0x0000000100a05b88 does not define or inherit an implementation of the resolved method 'abstract void register(com.mojang.brigadier.CommandDispatcher, net.minecraft.class_7157, net.minecraft.class_2170$class_5364)' of interface dev.architectury.event.events.common.CommandRegistrationEvent.

**Comment by wpatrickhames** [comment]
Yeah that looks like it:

The game crashed whilst mouseclicked event handler
Error: java.lang.AbstractMethodError: Receiver class draylar.identity.command.IdentityCommand$$Lambda$3693/0x0000000100a01f78 does not define or inherit an implementation of the resolved method 'abstract void register(com.mojang.brigadier.CommandDispatcher, net.minecraft.class_7157, net.minecraft.class_2170$class_5364)' of interface dev.architectury.event.events.common.CommandRegistrationEvent.
Exit Code: -1

**Comment by Shadowysn** [comment]
[Temporary 1.19.1/1.19.2 update fix,](https://github.com/Draylar/identity/discussions/422) this link contains the compiled **.jar** file for use in **1.19.1** and **1.19.2**. Draylar doesn't seem to be active again.

**Comment by wpatrickhames** [comment]
Unfortunately. I wish I knew more about modding - I could patch something together.

**Comment by Shadowysn** [comment]
Sorry I didn't make it obvious, but I made a discussion containing a version of the mod that works for **1.19.1/2**. I linked it in my previous comment.

**Comment by wpatrickhames** [comment]
Doh - Thanks for that, Shadowysn! I've seen some of your previous posts talking about how you had a working version but never found a link. So awesome!!

**Comment by Draylar** [comment]
Fixed in the next release. Please send your thanks to Shadowysn and Alexthw46 for creating + compiling patches for this bug :)

**Comment by wpatrickhames** [comment]
Thanks @Shadowysn and @Alexthw46!
