### ISSUE TITLE
It wont work

### ISSUE THREAD

**Issue by janIpen** [Draylar/identity#419]
**Bug description**
*A description of what you expected to happen and what actually happened.*
I expect it to open
Instead, it crashed

**Game log:**
*Upload your game log through [hastebin](https://hastebin.com/) and provide the link. Do not paste the link directly into the submission box or comments.*
[log](https://hastebin.com/ukequlicag.sql)

**Modpack**
[It broke-1.0.zip](https://github.com/Draylar/identity/files/9380353/It.broke-1.0.zip)

**Comment by janIpen** [comment]
Error:
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install architectury, any version.
Unmet dependency listing:
	 - Mod 'Identity' (identity) 2.5.0-1.19 requires any version of architectury, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Natedogwoooof** [comment]
install arcatectury

**Comment by janIpen** [comment]
i thought gdlauncher did lol

**Comment by Draylar** [comment]
Arch can be found [here ](https://www.curseforge.com/minecraft/mc-mods/architectury-api) if you still need it :)
