### ISSUE TITLE
wont load when i open worlds

### ISSUE THREAD

**Issue by InvertedCandy14** [Draylar/identity#420]
well i keep getting an error when trying to load or create a world

I actually dont know how to use hastebin so heres the log
 The game crashed whilst mouseclicked event handler
Error: java.lang.AbstractMethodError: Receiver class draylar.identity.command.IdentityCommand$$Lambda$3623/0x0000000100a05b88 does not define or inherit an implementation of the resolved method 'abstract void register(com.mojang.brigadier.CommandDispatcher, net.minecraft.class_7157, net.minecraft.class_2170$class_5364)' of interface dev.architectury.event.events.common.CommandRegistrationEvent.

hope this helps

**Comment by Shadowysn** [comment]
[Temporary 1.19.1/1.19.2 update fix,](https://github.com/Draylar/identity/discussions/422) this link contains the compiled **.jar** file for use in **1.19.1** and **1.19.2**. Draylar doesn't seem to be active again.

**Comment by Draylar** [comment]
Fixed thanks to Shadowysn and Alexthw46!
