### ISSUE TITLE
Forge: missing code and request.

### ISSUE THREAD

**Issue by 78codemonkey** [Draylar/identity#426]
**Bug description**
Some of vanilla creatures are not implemented, like bat can't fly. Even check code in jar file and some are missing.
2 a request to support flying and water breathing to beteranimalsplus and Alexsmobs as well.
Tried to put code in myself but it just disables it al together, can still morph but nothing Flys or anything 

**Game log:**
Identity.jar/data/Identity/tags/entity_types/flying.json and undrownable.json

**Comment by zPanic** [comment]
@78codemonkey 

Figured out how to add custom mobs to the .json files.
Make sure to set "replace" to "true" at the top, see my examples attached

[flying undrownable.zip](https://github.com/Draylar/identity/files/9452748/flying.undrownable.zip)

**Comment by 78codemonkey** [comment]
ok, and here is the code written for most creatures for flying, water, lava walking and high temp
[ModSupport.zip](https://github.com/Draylar/identity/files/9456931/ModSupport.zip)

**Comment by 78codemonkey** [comment]
@zPanic  
Have to re-open post, anytime I put the new code in, models still don't fly or breathe under water with Vanilla or modded (if I delete edited .jar file and redownload identity (from curseforge), then the pre-set models work again. I even made new pack with only aqua-culture, Alex's mobs, better animals plus, Optifine, Architechery, Citidal, and JEI. In Modsupport file in recent comment is code that is made for most of the creatures. Not sure if I missed code set in another location.
I'm also using VS code and 7zip for editing.
