### ISSUE TITLE
How to use identity API on Fabric 1.19?

### ISSUE THREAD

**Issue by pgr4567** [Draylar/identity#431]
Hi there!
I am trying to integrate the identity mod into a fabric mod. If have added the jar as a dependency in my build.gradle file like so:
`modImplementation files("identity-2.6.0-1.19.1-fabric.jar")`

Everything works, however when trying to run the game, it crashes with the error saying omega config is missing. (NoClassDefFoundError: draylar/omegaconfig/api/Config)
However I did not find omegaconfig for version 1.19. I was wondering how this mod even uses omegaconfig as I could not find it in its build.gradle file.

Any help is appreciated, thanks!

**Comment by James103** [comment]
You may need to install https://github.com/Draylar/omega-config as a dependency for your mod as well.

**Comment by pgr4567** [comment]
True! I did not find the correct version! It is this for anyone wondering.
`modImplementation include ("com.github.Draylar.omega-config:omega-config-base:1.2.3-1.18.1") {
        exclude group: "net.fabricmc.fabric-api"
    }`
