### ISSUE TITLE
The mod is not working on the Forge Server 

### ISSUE THREAD

**Issue by Lordieee** [Draylar/identity#44]
The mod is working on singleplayer but in multiplayer it doesnt.. i research all the way how to do it but it doesnt work please help me ty  

MInecraft Version 1.16.1

**Comment by Draylar** [comment]
This is not a Forge mod. Are you running it on a Forge server or a Fabric server? I need a game log to help. upload it to a site such as hastebin or pastebin, them send the link.

**Comment by Lordieee** [comment]
I am running a Forge server.. it is working in singleplayer with fabric loader

**Comment by Draylar** [comment]
You can't run this mod on a Forge server. You need the Fabric server found [here](https://fabricmc.net/use/) instead. Forge and Fabric are separate mod loaders and will not work together (you have to choose one or the other).

**Comment by Lordieee** [comment]
Thank u so much its working now :3
