### ISSUE TITLE
minecraft fabric 1.18.2 latest mod version invisible and can't load back to my skin and left in steave

### ISSUE THREAD

**Issue by Foxsyl** [Draylar/identity#468]
so i just making my modpack and add this mod but when i try it it work wine except when i want come back to human form i try command and gui but i come back to steve skin not mine and in log it say
[Worker-Main-9/ERROR]: triggerSkinDownload()3 failed for player:Foxsylretrying again later
and i create new world and i am invisible xd

[latest.log](https://github.com/Draylar/identity/files/10197986/latest.log)

**Comment by Foxsyl** [comment]
idk what i did but i restart computer and it work for now

**Comment by Natedogwoooof** [comment]
Steve?
