### ISSUE TITLE
Players morphed as Foxes get hurt by sweet berry bushes and slowed down

### ISSUE THREAD

**Issue by realflow100** [Draylar/identity#47]
Players morphed as foxes do not have immunity to sweet berry bushes.

I'm guessing this would be a very low priority issue to solve. 
Sorry if its pointless for me to submit this issue.

**Comment by Draylar** [comment]
Fixed in 1.9.2, thanks :)

**Comment by realflow100** [comment]
YAY!!!!!!
small edit note: your no longer hurt by sweet berries when morphed as a fox but still slowed down by the berry bushes. in case anyone sees this.
