### ISSUE TITLE
Foxes and berry bushes (again) still slowed down.

### ISSUE THREAD

**Issue by realflow100** [Draylar/identity#48]
being hurt is fixed with the new identity update but it seems you still get slowed down while inside the berry bushes when morphed as a fox

I mainly play on a multiplayer server with this mod and a few friends.
Tried in a new fresh singleplayer world as well.

**Comment by Draylar** [comment]
Fully fixed in the next release, as well as the same patch for Bees (because apparently Bees aren't slowed or hurt by bushes as well)!
