### ISSUE TITLE
Idle sounds option/toggle for players morphed as mobs?

### ISSUE THREAD

**Issue by realflow100** [Draylar/identity#49]
Could be a cool thing. being able to turn on/off morph mob idle sounds.
like the zombie groan. chicken clucking. ect.
Possibly toggle-able in-game per-player or per-morph even? that would be pretty epic

**Comment by Draylar** [comment]
Out in the next update, with the `playAmbientSounds` and `hearSelfAmbient` options available for customization (default: true, false). Thanks for the suggestion!
