### ISSUE TITLE
Mod dependency version?

### ISSUE THREAD

**Issue by mcjojo3** [Draylar/identity#507]
Yo, I'm developing a mod which plans to implement character morphing but I want it to be fully controlled by the other mod in question. I am wondering if that would be possible or if you'd let me fork the mod to modify it.

Cheers

**Comment by mcjojo3** [comment]
As this isn't a bug I'm sorry but I couldn't find anywhere to contact you outside of CurseForge but from experience a lot of people don't really check their inboxes.

**Comment by Draylar** [comment]
Are you looking for a gradle dependency? I can look into publishing it to my maven if that would help. Otherwise, you are more than welcome to make a fork (the license of this project is MIT).

**Comment by mcjojo3** [comment]
> Otherwise, you are more than welcome to make a fork (the license of this project is MIT).

Thank you! Basically I want to modify this mod to only allow entity changing through commands & calls for a mod I'm working on. 😁

**Comment by Natedogwoooof** [comment]
Love your mod Draylar
