### ISSUE TITLE
Please help me fix this 

### ISSUE THREAD

**Issue by akbarinto1** [Draylar/identity#542]
![IMG-20230608-WA0004](https://github.com/Draylar/identity/assets/135954510/ebfa6d79-0fae-4f4c-935c-39586cfa9c23)

**Comment by Natedogwoooof** [comment]
not even Minecraft  Related

**Comment by Draylar** [comment]
Hi akbarinto1, I think the best spot to put this issue would be on the [issue tracker for the project](https://github.com/technopremium/avatarify-python-youtube/pulls). Best of luck in your hunt for a solution.
