### ISSUE TITLE
Gane Crash

### ISSUE THREAD

**Issue by GevaX** [Draylar/identity#565]
**Bug description**
*i pressed the ` key to Identity instantly when i pressed my game crashed*

**Game log:**
*[[Upload your game log through [hastebin](https://hastebin.com/) and provide the link. Do not paste the link directly into the submission box or comments](https://hastebin.com/share/ihibolayev.php).](https://hastebin.com/share/ihibolayev.php)*

**Comment by sacu85** [comment]
Try my modified jar file: https://github.com/Draylar/identity/issues/552#issuecomment-1626370217
