### ISSUE TITLE
Should abilities be triggered by a key-bind or stay as is?

### ISSUE THREAD

**Issue by Draylar** [Draylar/identity#59]
Should Identity abilities stay as is (use an item to trigger ability), or should they move to a key-bind? The keybind would have no cost but would have a cooldown depending on the ability power and type.

**Comment by realflow100** [comment]
i think its less OP when requiring an item.
but a keybind is quite an enticing option.
Maybe an option or combination of both? requiring an item to be held to use the ability in some way? some way thats not too OP but doesnt make the abilities useless?

**Comment by Ashtar084** [comment]
yes, it will be much better a key to use the skill
