### ISSUE TITLE
Phantom is Unable to fly

### ISSUE THREAD

**Issue by Nexans20** [Draylar/identity#6]
Phantom Identity can't fly and takes fall damage.

**Comment by Draylar** [comment]
Fixed in 1.1.0 beta ([GH](https://github.com/Draylar/identity/releases/tag/1.1.0-beta-1.16), [CF](https://www.curseforge.com/minecraft/mc-mods/identity/files/2990840)) alongside a change that fixes the pitch of Phantoms (previously, looking up meant the Phantom looked down). Thanks for the report!
