### ISSUE TITLE
Identity Cause Crash

### ISSUE THREAD

**Issue by zikehalil3535** [Draylar/identity#640]
**Bug description**
*A description of what you expected to happen and what actually happened.*
Identity cause crash after start the game.
**Game log:**
*Upload your game log through [hastebin](https://hastebin.com/) and provide the link. Do not paste the link directly into the submission box or comments.*
https://hastebin.com/share/lefifoyahe.bash
https://hastebin.com/share/yoxesijuta.css

**Comment by ToCraft** [comment]
Did you play on 1.20.1+?
