### ISSUE TITLE
Identity Crashes On Forge 1.20.1

### ISSUE THREAD

**Issue by SynergyDeveloper** [Draylar/identity#642]
Im working on a modpack for forge 1.20.1, i have tried both versions of identity but the game opens for a few seconds, then closes, there are no errors in the logs, only warnings in the log, without identity it works fine, i have tried multiple forge versions

**Comment by SynergyDeveloper** [comment]
found a work around, yes i did try before opening this.

**Comment by etherealgears** [comment]
What was the workaround? I'm having this issue too and can't figure out how to fix it.

**Comment by Golden-Dragon161** [comment]
Please what was the solution, facing the same problem with probably the same output log, 
please tell me
@SynergyDeveloper

**Comment by Natedogwoooof** [comment]
> What was the workaround? I'm having this issue too and can't figure out how to fix it.

install woodwalkers and crafted core and remorphed

**Comment by TechnicallyMC** [comment]
thats what i did, i just didnt see these messages
(this is my alt account)
