### ISSUE TITLE
Max health desync when dying as a non-human Identity

### ISSUE THREAD

**Issue by James103** [Draylar/identity#72]
As of Minecraft 1.16.3 and Identity 1.10.0, when you die and respawn as an Enderman, Turtle, Evoker, Witch, or similar, you get a max health desync. If the natural regeneration gamerule is turned on, this is evident in that it appears that you have 20 HP max health and 20 food points, but after a few seconds, the displayed max health stays the same but the food level drops to 17 food points.

**Comment by Draylar** [comment]
Fixed in next release 👍
