### ISSUE TITLE
flying bug

### ISSUE THREAD

**Issue by resourcepackadiego** [Draylar/identity#78]
This mod is on my aternos server (1.16.4 fabric). After installing this mod I noticed that I can "fly" as every mob (except spider) and even player. I fall slowly, but I take fall damage. EDIT: Changing the config file isn't working too. I always have the default ones.

**Comment by Draylar** [comment]
Every weird/non-reproducible bug I have received for this mod occurs on an Aternos server. Check your server logs for errors and make sure the mod is installed on both the server and the client. There isn't much I can do about this unless it is reproducible on a vanilla server/client.
