### ISSUE TITLE
Cooldown animation for Identity item ability is unusual

### ISSUE THREAD

**Issue by James103** [Draylar/identity#8]
Minecraft 1.16.1
Fabric 0.8.8+build.202
LWJGL 3.2.2
Fabric API 0.14.0+build.371-1.16
Identity 1.0.3-beta-1.16

When disguised as a Ghast and holding some Fire Charges, using one causes a cooldown animation that looks like this:
![image](https://user-images.githubusercontent.com/37945304/85932046-6c4bdf80-b88e-11ea-8251-d20b63fdf767.png)

For other player item usage, it looks like this:
![image](https://user-images.githubusercontent.com/37945304/85932058-85549080-b88e-11ea-90b5-13ecd895aa76.png)

**Comment by Draylar** [comment]
Fixed in 1.1.0-beta ([GH](https://github.com/Draylar/identity/releases/tag/1.1.0-beta-1.16), [CF](https://www.curseforge.com/minecraft/mc-mods/identity/files/2990840)). Thanks for the report!
