### ISSUE TITLE
Incompatibility with Blast mod

### ISSUE THREAD

**Issue by defenestrationdude** [Draylar/identity#80]
[crash-2020-12-21_05.05.01-client.txt](https://github.com/Draylar/identity/files/5726373/crash-2020-12-21_05.05.01-client.txt)

Trying to use the Identity menu while also running Blast caused the game to crash before the menu came up.

**Comment by Draylar** [comment]
This is a issue with BLAST, Identity just happens to accelerate the crash-finding process. It seems the author fixed it in a recent commit, but I'm not sure if that has been released or not.
