### ISSUE TITLE
Crash when run alongside Pehkui

### ISSUE THREAD

**Issue by Bombbery** [Draylar/identity#82]
Identity, with paired with _Pehkui_, will cause a crash when a world is generating.

**Crash Log:** https://pastebin.com/phzL1jp8
(Sorry if this is an issue on Pehkui's end, I wasn't sure which mod I should post the issue to)

**Comment by James103** [comment]
Have you made sure that Identity, Pehkui, Fabric loader, and Fabric API are all fully updated? Does the crash still occur if only the aforementioned mods are loaded?

**Comment by Bombbery** [comment]
Mentioned mods are up to date, with the following versions:

**API**: 0.29.2 
**Identity**: 1.10.2
**Pehkui:**: 1.6.2 

Tested with just these two mods and the API and loader, same issue.

**Comment by Draylar** [comment]
IIRC [this version](https://github.com/Virtuoel/Pehkui/releases/tag/1.7.0%2B20w51a) of Pehkui solves the issue.

**Comment by Draylar** [comment]
![image](https://user-images.githubusercontent.com/17728338/103490393-19288b80-4de1-11eb-9c8a-b61478e445cd.png)

**Comment by Bombbery** [comment]
Yup, this resolved the issue, thanks!
