### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by evoid123** [Draylar/identity#85]
I try to use the mod, and it just doesn't work. I have checked and other mods work, but just not Identity (1.16.4) I am using Fabric api 1.16.4 and also tried 1.16.3 but no luck.

**Comment by evoid123** [comment]
![Capture](https://user-images.githubusercontent.com/77027554/103703591-cc29ee00-4f75-11eb-8e53-973b3f6054d9.PNG)

**Comment by Draylar** [comment]
Can you send your game log through hastebin (https://hastebin.com)?

**Comment by evoid123** [comment]
I copy pasted it but im not sure how to send it to you as I have never used it before.

**Comment by evoid123** [comment]
nevermind, here https://hastebin.com/harepexado.sql

**Comment by evoid123** [comment]
Problem fixed, but now i am wondering what the action key is as I cannot see anything about it in the desc.

**Comment by James103** [comment]
By default (US English), it's the grave/tilde key.

**Comment by evoid123** [comment]
> By default (US English), it's the grave/tilde key.
When I click on it, it shows the identity's I have, but how do I for example teleport as an enderman, or shoot fireballs as a blaze.

**Comment by James103** [comment]
The identity abilities require that you use specific items using the regular item use key. For example, blaze fireballs cost blaze powder, enderman teleports cost ender pearls, wither shooting skulls requires wither skulls, etc.

**Comment by evoid123** [comment]
Oh ok thank you.

**Comment by Draylar** [comment]
Thanks for the help, James! Highly appreciated.

**Comment by TheServerit** [comment]
> The identity abilities require that you use specific items using the regular item use key. For example, blaze fireballs cost blaze powder, enderman teleports cost ender pearls, wither shooting skulls requires wither skulls, etc.

There's a button for the abilities. it's just R.
