### ISSUE TITLE
Unplayable Server

### ISSUE THREAD

**Issue by iGreenDogs** [Draylar/identity#87]
Hello, I have successfully opened a server on my computer and joined it. Then, after my friend downloaded ALL of the needed files, she was able to join but was kicked instantly. We tested it, and it worked on her single player worlds, but still got kicked out of my server. Please Help (BTW, I have Windows 10 and she has a Mac)

**Comment by James103** [comment]
1. What is the message that you get on the disconnect screen?
2. Do you have full logs from server and client to post here?
3. Have you made sure that the Minecraft installation on the server is the exact same as the Minecraft installation on the client, despite the different platforms?

**Comment by nemoyatpeace** [comment]
I'm adding this here because my issue is similar.  I have been enjoying this with my son, we've played a few sessions after installing them a couple days ago, me on my Mac and him on Windows.  But, the last couple sessions, we've had trouble switching identities.  When toggling the screen it causes the game to crash.  Sometimes it works fine, but usually it doesn't and the only way we've been able to get past the crash is to first summon a new creature to kill and unlock an identity, then we can switch, but even this only lasts for a while before the next switch causes a crash again.  We've both unlocked about 40 identities.

**Comment by James103** [comment]
@nemoyatpeace Do you have the crash logs as well?

**Comment by nemoyatpeace** [comment]
Unfortunately no, will get them next time it happens.  As I think about it, one of the crash times my son wasn't even connected.  I just attempted to swap again, this time, just running it on my own on my Mac.  Crashed again when I tried to bring up the identity menu.

`---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/6/21 10:11 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:777)
	at java.util.TimSort.mergeAt(TimSort.java:514)
	at java.util.TimSort.mergeCollapse(TimSort.java:441)
	at java.util.TimSort.sort(TimSort.java:245)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at draylar.identity.screen.IdentityScreen.<init>(IdentityScreen.java:50)
	at draylar.identity.IdentityClient.lambda$onInitializeClient$0(IdentityClient.java:44)
	at net.minecraft.class_310.handler$zzk000$onStartTick(class_310.java:2881)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.TimSort.mergeLo(TimSort.java:777)
	at java.util.TimSort.mergeAt(TimSort.java:514)
	at java.util.TimSort.mergeCollapse(TimSort.java:441)
	at java.util.TimSort.sort(TimSort.java:245)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at draylar.identity.screen.IdentityScreen.<init>(IdentityScreen.java:50)
	at draylar.identity.IdentityClient.lambda$onInitializeClient$0(IdentityClient.java:44)
	at net.minecraft.class_310.handler$zzk000$onStartTick(class_310.java:2881)

-- Affected level --
Details:
	All players: 1 total; [class_746['MinceAraft'/96, l='ClientLevel', x=-2934.31, y=62.00, z=-4129.26]]
	Chunk stats: Client Chunk Cache: 529, 50
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,208), Chunk: (at 0,4,0 in 0,13; contains blocks 0,0,208 to 15,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 279078 game time, 37507 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Mac OS X (x86_64) version 10.15.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1189511448 bytes (1134 MB) / 1979711488 bytes (1888 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		cardinal-components-base: Cardinal Components API (base) 2.7.1
		cardinal-components-entity: Cardinal Components API (entities) 2.7.1
		fabric: Fabric API 0.29.1+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.1+36111fa03a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.2.0+cbe9176f3a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+cbe9176f3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+c26373133a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.0+552549d53a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		identity: Identity 1.10.2-beta-1.16.3
		io_github_onyxstudios_cardinal-components-api: Cardinal-Components-API 2.7.1
		minecraft: Minecraft 1.16.4
		playerabilitylib: Pal 1.2.1
	Launched Version: fabric-loader-0.10.8-1.16.4
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Intel(R) Iris(TM) Plus Graphics OpenGL Engine GL version 2.1 INTEL-14.6.18, Intel Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	GPU Warnings: version: 2.1
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz`

**Comment by iGreenDogs** [comment]
`1. What is the message that you get on the disconnect screen?`
`2. Do you have full logs from server and client to post here?`
`3. Have you made sure that the Minecraft installation on the server is the exact same as the Minecraft installation on the client, despite the different platforms?`
>1.  I only have the server side
>>[18:31:42] [Server thread/INFO]: Periwinkle9032[/98.110.167.191:49567] logged in with entity id 245 at (157.5, 73.0, 55.5)
>>[18:31:43] [Server thread/INFO]: Periwinkle9032 joined the game
>>[18:31:43] [Server thread/INFO]: Periwinkle9032 lost connection: Disconnected
>>[18:31:43] [Server thread/INFO]: Periwinkle9032 left the game
>2. [https://pastebin.com/xC7kXty4](https://pastebin.com/xC7kXty4)              Just so you know, I was playing around when she was installing
>3. Yes

**Comment by Draylar** [comment]
It's hard to tell if this is another instance of Macs being weird, or the mod being bugged. I am leaning towards the first option because Macs are... kind of notorious for causing random issues in mods. I have received a few similar reports from Mac users in the past. Just to narrow down the problem, I tested LAN between my PC and laptop (both Windows), and couldn't reproduce any issues.

re: iGreendogs' log, there isn't much information in it. If you could get the log from the client, it might have more clues. I am working on an update now that:
- catches issues with sorting in the menu (won't crash with that first log)
- updates all dependency versions to remove any chance for conflicts or dependency changes
- fully built on 1.16.4

I doubt this will fix anything, but it might help to narrow down the problem again.

**Comment by iGreenDogs** [comment]
Hello everyone, I have the log files from my friend's client-side
https://pastebin.com/NZwxVxy4

Hope you can continue to help
THX, iGreenDogs

**Comment by Draylar** [comment]
iGreenDogs, you have Identity 1.10.2 on the latest log, and 1.10.1 on the first log. Do all clients and the server have the same version of Identity?

**Comment by iGreenDogs** [comment]
Hello Draylar, I will test that later today (after I noticed that I DON'T have the latest version on my computer and we both did not touch anything since download. Thanks for your help and I will close this issue if it works 😸
