### ISSUE TITLE
Health is not scaled when changing Identities

### ISSUE THREAD

**Issue by James103** [Draylar/identity#9]
Minecraft 1.16.1
Fabric 0.8.8+build.202
LWJGL 3.2.2
Fabric API 0.14.0+build.371-1.16
Identity 1.0.3-beta-1.16

Regardless of your current Identity, your max health is always at 20 unless changed via effects or commands. In similar mods for 1.12.2, your max health depends on your current morph (called Identity here), and changing your morph (Identity) scaled your current health by the ratio of your old max health to new max health.

Example 1: Change Identity: Player -> Chicken, current health is 12 HP before change
Expected Result: Max Health = 4 HP, Current Health = 2.4 HP

Example 2: Change Identity: Chicken -> Wither, current health is 0.04 HP before change
Expected Result: Max Health = 300 HP, Current Health = 3 HP

Example 3: Change Identity: Wither -> Player, current health is 88 HP before change
Expected Result: Max Health = 20 HP, Current Health = 5.866... HP

**Comment by Draylar** [comment]
Just implemented Health Scaling in 1.7.0. It's not a percentage, instead, it looks like this:
- Wither 300HP -> Chicken = 4 health
- Chicken full hp -> Wither = 4 health
Wither 1HP -> Chicken = 1 Health

The reason for this is so you can't swap to a Chicken, regen health instantly, then swap back to a Wither to instantly regain 200~ HP.
