### ISSUE TITLE
Creeper stuck in explosion sequence and just flashing a greenish-white

### ISSUE THREAD

**Issue by apatheticgenesis** [Draylar/identity#94]

**Comment by Draylar** [comment]
![image](https://user-images.githubusercontent.com/17728338/104509785-c6ed2480-55af-11eb-9460-fa460d90e85b.png)

Not able to reproduce on 1.11.0. Could you send me your game log through [hastebin](https://hastebin.com/)?

**Comment by Draylar** [comment]
Feel free to re-open this issue if you experience it again on the latest versions.
