### ISSUE TITLE
fabrick indicates that the file must contain name fabrick

### ISSUE THREAD

**Issue by ToastedPanda** [Draylar/identity#98]
when I start minecraft fabrick and have the mod in the mods folder, fabrick says that the name of the file must be fabrick
![Knipsel](https://user-images.githubusercontent.com/77457547/104629811-448d5f00-569a-11eb-89c1-d60f7eed7f1f.PNG)

**Comment by Draylar** [comment]
Install Fabric API (https://www.curseforge.com/minecraft/mc-mods/fabric-api).
